add linq methods
neo-project/neo-devpack-dotnet pull request #1001
Opened 2024-03-25 05:51 UTC by Ashuaidehao

Add some linq methods.

2024-03-25 09:54 UTC, shargon commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +            return Any(source, s => s.Equals(value));
this Equals works?

2024-03-25 10:07 UTC, Ashuaidehao commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +            return Any(source, s => s.Equals(value));
It works good in UTs with `int`, not test with custom types yet.

2024-03-25 11:18 UTC, shargon approved these changes

2024-03-25 11:42 UTC, vncoelho commented on tests/Neo.Compiler.CSharp.TestContracts/Neo.Compiler.CSharp.TestContracts.csproj
> -        <Nullable>enable</Nullable>
why this difference?

2024-03-25 11:44 UTC, Ashuaidehao commented on tests/Neo.Compiler.CSharp.TestContracts/Neo.Compiler.CSharp.TestContracts.csproj
> -        <Nullable>enable</Nullable>
Some auto-format issue by IDE.

2024-03-25 11:47 UTC, vncoelho commented on tests/Neo.Compiler.CSharp.TestContracts/Contract_Linq.cs
> +    public class Contract_Linq : SmartContract.Framework.SmartContract
These tests looks good

2024-03-25 11:48 UTC, vncoelho commented on tests/Neo.Compiler.CSharp.TestContracts/Neo.Compiler.CSharp.TestContracts.csproj
> -        <Nullable>enable</Nullable>
maybe move to another PR, it is strange because we have the default format for the project. Maybe something need to be modified to have a general fix.

2024-03-25 11:50 UTC, vncoelho commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_Linq.cs
> +            Assert.AreEqual(-100, result[0]);
In this correct?

2024-03-25 11:52 UTC, vncoelho commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_Linq.cs
> +            Assert.AreEqual(-100, result[0]);
Yes, it is correct.

I see, maybe add  as well
Assert.AreEqual(100, result[3]);

2024-03-25 11:57 UTC, vncoelho commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_Linq.cs
> +            Assert.AreEqual(-100, result[0]);
```suggestion
            Assert.AreEqual(-100, result[0]);
            Assert.AreEqual(100, result[3]);
```

2024-03-25 11:58 UTC, vncoelho commented on tests/Neo.Compiler.CSharp.TestContracts/Contract_Linq.cs
> +        public static bool AllGreatThanZero(int[] array)
@Jim8y 
maybe rename all these...kkkkkkkkkkk

2024-03-25 12:03 UTC, Jim8y commented on tests/Neo.Compiler.CSharp.TestContracts/Contract_Linq.cs
> +        public static bool AllGreatThanZero(int[] array)
at your service

2024-03-25 12:20 UTC, Jim8y submitted a review, later dismissed

2024-03-26 14:15 UTC, Jim8y approved these changes

2024-03-26 14:23 UTC, cschuchardt88 requested changes

2024-03-26 14:23 UTC, cschuchardt88 commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
Move this to project [Neo.Extensions](https://github.com/neo-project/neo)

2024-03-26 14:23 UTC, cschuchardt88 commented on tests/Neo.Compiler.CSharp.TestContracts/Neo.Compiler.CSharp.TestContracts.csproj
> +  </ItemGroup>
```suggestion

```

Remove this as well

2024-03-26 14:23 UTC, cschuchardt88 commented on tests/Neo.Compiler.CSharp.TestContracts/Neo.Compiler.CSharp.TestContracts.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
```suggestion
```
Note you will have to add all the namespaces to each `*.cs` here in this project...

2024-03-26 15:27 UTC, Jim8y commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
this is for contract compiler, not the core.

2024-03-26 15:28 UTC, Jim8y submitted a review, later dismissed

2024-03-26 16:58 UTC, cschuchardt88 commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
But it does basic generic functions that are reusable that could be shared across  applications for neo.

2024-03-27 02:44 UTC, Ashuaidehao commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
These methods are imitate copy from `System.Linq`, cannot be reusable for normal projects except for smart contracts.

2024-03-27 07:50 UTC, shargon commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
But maybe we use syscalls inside

2024-03-27 07:51 UTC, shargon submitted a review, later dismissed

2024-03-27 07:51 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +            //if (source is T[] array) return array.Length;
This commented code can be removed then.

2024-03-27 07:51 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +            //if (source is T[] array) return array.Length;
Ditto.

2024-03-27 07:51 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +        /// <returns>An collection whose elements are the result of invoking the transform function on each element of source.</returns>
```suggestion
        /// <returns>An collection whose elements are the result of invoking the transform function on each element of source.</returns>
        /// <exception cref="ArgumentNullException"></exception>
```

2024-03-27 07:51 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +        public static IEnumerable<T> Skip<T>(this IEnumerable<T> source, int count)
Add `/// <exception cref="ArgumentNullException"></exception>` to doc.

2024-03-27 07:51 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +        public static int Sum(this IEnumerable<int> source)
Add `/// <exception cref="ArgumentNullException"></exception>` to doc.

2024-03-27 07:51 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +        public static int Sum<T>(this IEnumerable<T> source, Func<T, int> selector)
Add `/// <exception cref="ArgumentNullException"></exception>` to doc.

2024-03-27 07:51 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +        public static int Sum<T>(this IEnumerable<T> source, Func<T, int> selector)
Here and below for the rest of methods that use `AssertSourceNotNull`.

2024-03-27 07:54 UTC, AnnaShaleva reviewed
Really good job, these APIs are useful.

2024-03-27 07:54 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +        public static Map<TKey, TValue> ToMap<TSource, TKey, TValue>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TValue> elementSelector)
Missing `summary` doc.

2024-03-27 11:12 UTC, Jim8y commented on src/Neo.SmartContract.Framework/Linq/LinqExtensions.cs
> +        ///  Computes the average of a sequence of System.Int32 values.
This is for contract that use C#, so i think C# syntax should be better as developer will not care much about neo type or C# type, they should only care about C# type.

2024-03-27 11:23 UTC, shargon approved these changes

2024-03-27 11:29 UTC, AnnaShaleva approved these changes

2024-03-27 11:33 UTC, merged