Update to net 8
neo-project/neo-devpack-dotnet pull request #1004
Opened 2024-03-25 16:42 UTC by shargon

2024-03-25 16:48 UTC, cschuchardt88 commented
You need to change `main.yml` to `DOTNET_VERSION: 8.0.x`

2024-03-25 16:55 UTC, Jim8y commented on .github/workflows/main.yml
> +  DOTNET_VERSION: 8.0.x
dev-container as well?

2024-03-25 17:00 UTC, shargon commented on .github/workflows/main.yml
> +  DOTNET_VERSION: 8.0.x
done

2024-03-25 17:02 UTC, cschuchardt88 commented on .github/workflows/main.yml
> +  DOTNET_VERSION: 8.0.x
`global.json`

2024-03-25 17:19 UTC, Jim8y approved these changes

2024-03-25 17:22 UTC, shargon commented
mmm... coverage 0%

2024-03-25 17:23 UTC, Jim8y commented
> mmm... coverage 0%

Hahahahahahahhahahahhahahahhahhahahaha

2024-03-25 17:26 UTC, cschuchardt88 requested changes

2024-03-25 17:26 UTC, cschuchardt88 commented on .github/workflows/main.yml
> +        dotnet pack --configuration Debug ./src/Neo.SmartContract.Template/Neo.SmartContract.Template.csproj
```suggestion
        dotnet pack ./src/Neo.SmartContract.Template/Neo.SmartContract.Template.csproj --configuration Debug
```

2024-03-25 17:26 UTC, cschuchardt88 commented on .devcontainer/devcontainer.json
> +  }
Can you please not change the spacing?

2024-03-25 17:26 UTC, cschuchardt88 commented on src/Neo.SmartContract.Analyzer/Neo.SmartContract.Analyzer.csproj
> +		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
Change spacing back

2024-03-25 17:26 UTC, cschuchardt88 commented on tests/Directory.Build.props
> +	</ItemGroup>
Change spacing back

2024-03-25 17:29 UTC, shargon commented on .devcontainer/devcontainer.json
> +  }
I didn't do nothing special, just my visual studio...

2024-03-25 17:30 UTC, shargon commented on src/Neo.SmartContract.Analyzer/Neo.SmartContract.Analyzer.csproj
> +		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
visual studio format this file like that....

2024-03-25 17:37 UTC, shargon commented
I don't know why it doesn't test anything... :S, @cschuchardt88 @Jim8y feel free to commit your changes

2024-03-25 17:49 UTC, AnnaShaleva commented on tests/Neo.SmartContract.Framework.TestContracts/Neo.SmartContract.Framework.TestContracts.csproj
> -        <TargetFramework>net7.0</TargetFramework>
Just a question: why don't we need a target framework for test contracts?

2024-03-25 18:37 UTC, cschuchardt88 commented on tests/Neo.SmartContract.Framework.TestContracts/Neo.SmartContract.Framework.TestContracts.csproj
> -        <TargetFramework>net7.0</TargetFramework>
The configurations are stored in `Directory.Build.props` file 
https://github.com/neo-project/neo-devpack-dotnet/blob/master/tests/Directory.Build.props

2024-03-26 12:05 UTC, superboyiii commented
Can any of you guys successfully run the unit test on **windows**? I update MSBuild to v17.9.0, MSBuild Toolset to v17.9.0, .NET SDK to v8.0.3, but it still returns error that "The following test container was not found: 'E:\PR-test\devpack-PR#1004\superboy\neo-devpack-dotnet\tests\Neo.Compiler.CSharp.UnitTests\bin\Debug\net8.0\Neo.Compiler.CSharp.UnitTests.dll'" .
I'm running test cases by Visual Studio Visual Studio 2022 v17.9.4

2024-03-26 12:17 UTC, cschuchardt88 commented
> Can any of you guys successfully run the unit test on **windows**? I update MSBuild to v17.9.0, MSBuild Toolset to v17.9.0, .NET SDK to v8.0.3, but it still returns error that `"The following test container was not found: 'E:\PR-test\devpack-PR#1004\superboy\neo-devpack-dotnet\tests\Neo.Compiler.CSharp.UnitTests\bin\Debug\net8.0\Neo.Compiler.CSharp.UnitTests.dll'"` . I'm running test cases by Visual Studio Visual Studio 2022 v17.9.4

@shargon @superboyiii 
Set `global.json` settings to this `"rollForward": "disable",` and make sure you have `8.0.202` installed... `8.0.203` doesn't not have support for `Visual Studio`.

2024-03-27 02:49 UTC, superboyiii commented
> `8.0.203` doesn't not have support for `Visual Studio`.

But why unit tests work on neo-modules? I run these by visual studio as well...
![65850a5ea6f13d56f27615629ccd63b](https://github.com/neo-project/neo-devpack-dotnet/assets/38493437/cab45877-d119-4784-9228-a5a2725a945a)

2024-03-27 07:44 UTC, shargon commented on .devcontainer/devcontainer.json
> +  }
done

2024-03-27 07:44 UTC, shargon commented on src/Neo.SmartContract.Analyzer/Neo.SmartContract.Analyzer.csproj
> +		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
done

2024-03-27 07:45 UTC, shargon commented on tests/Directory.Build.props
> +	</ItemGroup>
done

2024-03-27 07:45 UTC, shargon commented
I don't know why we have coverage 0%

2024-03-27 07:52 UTC, shargon commented
Solved

2024-03-27 10:47 UTC, cschuchardt88 requested changes

2024-03-27 10:47 UTC, cschuchardt88 commented on tests/Neo.SmartContract.Analyzer.UnitTests/Neo.SmartContract.Analyzer.UnitTests.csproj
> +        <RootNamespace>Neo.SmartContract.Analyzer.UnitTests</RootNamespace>
```suggestion
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Neo.SmartContract.Analyzer.UnitTests</RootNamespace>
```

2024-03-27 10:48 UTC, shargon commented on tests/Directory.Build.props
>      <IsPackable>false</IsPackable>
```suggestion
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
```

2024-03-27 10:49 UTC, shargon commented on tests/Neo.SmartContract.Analyzer.UnitTests/Neo.SmartContract.Analyzer.UnitTests.csproj
> +        <RootNamespace>Neo.SmartContract.Analyzer.UnitTests</RootNamespace>
Done in DirectoryBuilds

2024-03-27 10:51 UTC, vncoelho commented on .github/workflows/main.yml
> +        dotnet ./src/Neo.Compiler.CSharp/bin/Debug/net8.0/nccs.dll ./src/Neo.SmartContract.Template/bin/Debug/oracle/OracleRequest.csproj -o ./tests/Neo.SmartContract.Template.UnitTests/templates/neo
Maybe set the paths as variables

2024-03-27 10:52 UTC, Jim8y commented
works on my windows machine

2024-03-27 11:22 UTC, shargon commented on .github/workflows/main.yml
> +        dotnet ./src/Neo.Compiler.CSharp/bin/Debug/net8.0/nccs.dll ./src/Neo.SmartContract.Template/bin/Debug/oracle/OracleRequest.csproj -o ./tests/Neo.SmartContract.Template.UnitTests/templates/neo
It follow the previous file, improvements can be in a different pr.

2024-03-27 11:34 UTC, Jim8y submitted a review, later dismissed

2024-03-27 13:33 UTC, Jim8y commented on tests/Neo.Compiler.CSharp.TestContracts/Neo.Compiler.CSharp.TestContracts.csproj
> +        <ImplicitUsings>enable</ImplicitUsings>
```suggestion
```

2024-03-27 13:38 UTC, Jim8y approved these changes

2024-03-27 13:42 UTC, merged