Migrate old ut
neo-project/neo-devpack-dotnet pull request #1028
Opened 2024-04-19 08:46 UTC by shargon

Last migration unit test part, it will be divided in different pr because it's too long, included in this PR:

- Migrate BasicBlock optimizer unit tests.
- Moved old test to OldEngine namespace.
- Created artifacts for future PR.
- Separate contracts that are designed not to be compiled into folders.

2024-04-19 10:01 UTC, shargon commented
@Jim8y Still receiving compilation errors in `EnsureArtifactsUpToDateInternal` :S

2024-04-19 12:59 UTC, Jim8y commented
Weird cause there were ordinary compile errors, why they did not show in the past but appear here? Like Interface not supported.

2024-04-19 13:05 UTC, Jim8y commented
I get it now, cause many test contracts that demonstrate invalid syntax in neo contract were not compiled if there is no unit test against them. but in your new test logic, all contract will be compiled, thus many many compile errors appear.

2024-04-19 14:11 UTC, Jim8y commented
Remainning issue is in the working/bin/sc generated file, i have no idea how they are generated by your test engine, but i think you can fix them now

2024-04-19 17:43 UTC, cschuchardt88 requested changes
Add the following to all **TEST PROJECTS** `*.csproj` files.
```xml
<IsPackable>false</IsPackable>
<IsTestProject>true</IsTestProject>
```

Example
---
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
</Project>
```

2024-04-22 12:42 UTC, shargon commented on tests/Neo.Compiler.CSharp.UnitTests/OldEngine/UnitTest_Types.cs
> +            // using var testengine = new TestEngine();
@Jim8y  Why these tests doesn't work?

2024-04-22 12:47 UTC, shargon commented
> I get it now, cause many test contracts that demonstrate invalid syntax in neo contract were not compiled if there is no unit test against them. but in your new test logic, all contract will be compiled, thus many many compile errors appear.

Could you move them to notWorking folder, I want to compile only the other folder

2024-04-22 12:57 UTC, Jim8y commented
> Could you move them to notWorking folder? I want to compile only the other folder

I am not sure it has any meaning or not to show `invalid` cases. Those contracts can not be compiled, but only creating confusion, such as there were an interface contract and corresponding unit tests, but actually neo does not support interface at all.

2024-04-22 13:01 UTC, shargon commented on tests/Neo.Compiler.CSharp.TestContracts/Working/Contract_MemberAccess.cs
> +
```suggestion
```

2024-04-22 19:50 UTC, cschuchardt88 commented on tests/Neo.Compiler.CSharp.UnitTests/TestCleanup.cs
> +            var root = Path.GetPathRoot(testContractsPath) ?? "";
You should use `FileInfo`
```csharp
var fileInfo = new FileInfo(fileName);
```

2024-04-23 03:54 UTC, Jim8y approved these changes

2024-04-23 04:04 UTC, merged