[Examples] remove examples from workflow and create a solution for examples.
neo-project/neo-devpack-dotnet pull request #1029
Opened 2024-04-20 02:26 UTC by Jim8y

Closes https://github.com/neo-project/neo-devpack-dotnet/issues/1027

2024-04-20 02:27 UTC, Jim8y commented
because examples will create artifacts for every example, it takes a long time, thus need to remove from the workflow. we can run it locally.

2024-04-20 08:29 UTC, cschuchardt88 commented
@Jim8y What is the problem with using
---
![image](https://github.com/neo-project/neo-devpack-dotnet/assets/8141309/1d27b868-46a4-45a9-a077-01e171c39e7d)

2024-04-20 08:35 UTC, cschuchardt88 requested changes
Please don't change the formatting...

2024-04-22 12:51 UTC, shargon commented on examples/Example.SmartContract.ContractCall.UnitTests/Example.SmartContract.ContractCall.UnitTests.csproj
> +    <PropertyGroup>
Agree with @cschuchardt88 and the format

2024-04-24 02:43 UTC, superboyiii approved these changes

2024-04-24 03:09 UTC, superboyiii commented
Looks good on my local environment.

2024-04-24 12:01 UTC, vncoelho approved these changes

2024-04-24 12:24 UTC, merged

2024-04-25 10:32 UTC, shargon reviewed
Good change