fix nullable
neo-project/neo-devpack-dotnet pull request #1042
Opened 2024-05-20 03:07 UTC by Jim8y

fix https://github.com/neo-project/neo-devpack-dotnet/pull/1041#pullrequestreview-2065152303

2024-05-20 04:36 UTC, Jim8y commented on tests/Neo.Compiler.CSharp.UnitTests/TestingArtifacts/Contract_NULL.cs
> +    public abstract bool? EqualNotNullA(IList<object>? value);
This is automatically generated by the test engine, not me.

2024-05-20 08:51 UTC, cschuchardt88 requested changes
## Missed some

### tests/Neo.Compiler.CSharp.TestContracts/Contract_ABISafe.cs
The field 'Contract_ABISafe.s' is assigned but its value is never used

### src/Neo.SmartContract.Analyzer/CollectionTypesUsageAnalyzer.cs
Dereference of a possibly null reference.

### src/Neo.SmartContract.Analyzer/BigIntegerUsingUsageAnalyzer.cs
Possible null reference argument for parameter 'root' in 'Document Document.WithSyntaxRoot(SyntaxNode root)'.

2024-05-20 08:51 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Native/ContractManagement.cs
Can you fix `The event 'ContractManagement.OnDeploy' is never used` in this file too?

2024-05-20 08:51 UTC, cschuchardt88 commented on tests/Neo.Compiler.CSharp.TestContracts/Contract_Array.cs
> +        public static object? TestStructArrayInit()
May want to check `Unreachable code detected` in this method.

2024-05-20 08:51 UTC, cschuchardt88 commented on tests/Neo.Compiler.CSharp.TestContracts/Contract_StaticByteArray.cs
> +        public static event Action<byte[]> OnEvent = default!;
Fix `The field 'Contract_StaticByteArray.OnEvent' is assigned but its value is never used`?

2024-05-20 08:52 UTC, shargon commented on src/Neo.SmartContract.Testing/Native/ContractManagement.cs
> +#pragma warning disable CS0067 // Event is never used
This event can be used

2024-05-20 08:52 UTC, shargon commented on src/Neo.SmartContract.Testing/Native/GAS.cs
> +#pragma warning disable CS0067 // Event is never used
This event can be used

2024-05-20 08:54 UTC, shargon commented on src/Neo.SmartContract.Analyzer/NepStandardAnalyzer.cs
> +#pragma warning restore CS8602 // Dereference of a possibly null reference.
```suggestion
            var attributeSyntax = root?.FindNode(diagnosticSpan).AncestorsAndSelf().OfType<AttributeSyntax>().FirstOrDefault();
```

2024-05-20 09:29 UTC, Jim8y commented on src/Neo.SmartContract.Testing/Native/ContractManagement.cs
> +#pragma warning disable CS0067 // Event is never used
This just disable the warning, wont affect its function.

2024-05-20 09:36 UTC, shargon approved these changes

2024-05-20 09:38 UTC, Jim8y commented on tests/Neo.Compiler.CSharp.TestContracts/Contract_Array.cs
> +        public static object? TestStructArrayInit()
That code is weird,,,,,kinda like for loop is not necessary at all,,,,,,

2024-05-20 23:50 UTC, Jim8y commented
@shargon  please allow me to stop this one from here, too many warnings (200 to go) to fix, will do the remaining in another pr.

2024-05-20 23:57 UTC, vncoelho commented on src/Neo.Compiler.CSharp/MethodConvert/Expression/Expression.cs
> +                        var strValue = (string)value!;
where do we ensure value is never null?

2024-05-21 02:11 UTC, Jim8y commented on src/Neo.Compiler.CSharp/MethodConvert/Expression/Expression.cs
> +                        var strValue = (string)value!;
we dont, this just fix the warning. the code still run as past.

2024-05-21 02:12 UTC, Jim8y commented on src/Neo.Compiler.CSharp/MethodConvert/Expression/Expression.cs
> +                        var strValue = (string)value!;
> where do we ensure value is never null?

i used to do null check, but turns out it just work as !

2024-05-21 03:07 UTC, cschuchardt88 approved these changes

2024-05-21 03:09 UTC, merged