Add UInt160 and UInt256
neo-project/neo-devpack-dotnet pull request #347
Opened 2020-09-02 09:01 UTC by ShawnYun

Close #208

2020-09-02 09:22 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
I think this is too complicated for a contract and may cost a huge amount of GAS.

2020-09-02 09:33 UTC, ShawnYun commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
Or we can add a InteropService?

2020-09-02 09:41 UTC, ShawnYun commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
For static variables, we can do the conversion in the compiler. 
But for function arguments, we can't get the parameter values at compile time.

2020-09-02 09:47 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
Can you give a scenario?

2020-09-02 10:07 UTC, ShawnYun commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
For example:
```
static readonly string NeoToken = "0xde5f57d430d3dece511cf975a8d37848cb9e0525";
```
we can get the "0xde5f57d430d3dece511cf975a8d37848cb9e0525" in Compiler.
But if we have a function:
```
        public static UInt256 TestUInt256(String str)
        {
            UInt256 result = str.HexStringToUInt256();
            return result;
        }
```
the Function arguments are passed in when the contract is called.
This is after compiling，so compiler can't handle it.

2020-09-02 10:28 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
But why do you use a `string` as the parameter? I think you should use `UInt256` directly.

2020-09-07 07:17 UTC, ShawnYun commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
On the other hand, the conversion is not used too often, so the GAS consumption is acceptable.

2020-09-07 07:54 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
> We can't use a UInt256 as a contract parameter.

Why?

2020-09-07 08:08 UTC, ShawnYun commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
You mean use `public static UInt256 TestUInt256(UInt256 str)` 
and we transfer a `String` as a parameter?

2020-09-07 20:16 UTC, devhawk commented on src/Neo.SmartContract.Framework/Helper.cs
> +        }
> We can't use a `UInt256` as a contract parameter.

Doesn't Neo already support using UInt160/256 as a contract parameter type? https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ContractParameterType.cs#L12

2020-09-17 20:51 UTC, devhawk commented
What's the progress on this? Can we get this in for Preview 4 https://github.com/neo-project/neo/issues/1936?

2020-09-17 21:35 UTC, devhawk commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_UInt.cs
> +        public static UInt160 TestUInt160(String str)
We should have tests that take a UInt160/256 as an input parameter too

2020-09-17 22:50 UTC, devhawk commented
We should also add ECPoint support to smart contract framework. It behaves similarly to UInt160/256. However, we might want to do this as a separate PR

2020-09-17 23:19 UTC, devhawk commented on src/Neo.Compiler.MSIL/FuncExport.cs
> +                case "Neo.SmartContract.Framework.UInt160":
Why are we returning UInt160/256 as a byte array?

2020-09-18 07:43 UTC, shargon commented on src/Neo.SmartContract.Framework/NonemitWithConvertAttribute.cs
> +        ToUInt160,
ToUInt256?

2020-09-19 01:39 UTC, devhawk requested changes
Obsoleted by https://github.com/neo-project/neo-devpack-dotnet/pull/362

2020-10-29 07:50 UTC, ShawnYun commented
As #362, Performing conversion through VM is expensive, so we can close it.

2020-10-29 07:50 UTC, closed without merging