Create Testengine executable
neo-project/neo-devpack-dotnet pull request #365
Opened 2020-09-21 14:35 UTC by meevee98

Created an executable for the TestEngine to allow other Neo compilers, even those that aren't written using C#, to run their tests with the same executing engine as the C# compiler.

2020-09-21 18:03 UTC, shargon commented on tests/Neo.Compiler.MSIL.UnitTests/Utils/TestSnapshot.cs
> +                ((TestDataCache<StorageKey, StorageItem>)this._Storages).Delete(pair.Key);
We can add a clear method in `TestDataCache`

2020-09-22 01:25 UTC, erikzhang commented on src/TestingEngine/TestingEngine.csproj
> +    <ProjectReference Include="..\..\tests\Neo.Compiler.MSIL.UnitTests\Neo.Compiler.MSIL.UnitTests.csproj" />
Why does an `exe` project refer to a unit test project?

2020-10-05 16:35 UTC, meevee98 commented on src/TestingEngine/TestingEngine.csproj
> +    <ProjectReference Include="..\..\tests\Neo.Compiler.MSIL.UnitTests\Neo.Compiler.MSIL.UnitTests.csproj" />
Sorry for the delay in answering you.
It's referring to the unit test project because it's there the `TestEngine` class.
I can move this class to the `exe` project and target it from the unit test project instead if you think this way is better.

2020-10-17 10:42 UTC, shargon commented on src/TestEngine/TestUtils/NeonTestTool.cs
>  namespace Neo.Compiler.MSIL.UnitTests.Utils
Change namespace?

2020-10-17 10:42 UTC, shargon commented on src/TestEngine/Program.cs
> +                result = BuildJsonException("One or more arguments are missing");
Show an example?

2020-10-17 10:42 UTC, shargon commented on src/TestEngine/Helper.cs
> +            json["gas_consumed"] = (new BigDecimal(testEngine.GasConsumed, NativeContract.GAS.Decimals)).ToString();
We agreed to use `gasconsumed` format in json properties

2020-10-17 10:42 UTC, shargon commented on src/TestEngine/Helper.cs
> +        public static JObject ToJson(this DataCache<StorageKey, StorageItem> storage)
We will need to initialize the storage, for fake balances for example.

2020-10-17 10:42 UTC, shargon commented on src/TestEngine/Program.cs
> +                    // if something went wrong while reading the json, inserts null in this argument position
show log or break the execution, it could produce test mistakes.

2020-10-29 14:52 UTC, meevee98 commented on src/TestEngine/Helper.cs
> +        public static JObject ToJson(this DataCache<StorageKey, StorageItem> storage)
I'm currently working on this

2020-11-25 18:53 UTC, lock9 commented
Hi. We use these features quite a lot, any chance we can have this reviewed/merged?

2020-12-01 18:24 UTC, lock9 commented
![image](https://user-images.githubusercontent.com/38396062/100781000-3ab0e480-33e9-11eb-8bbd-8787e8be93d9.png)

2020-12-09 08:54 UTC, shargon commented
I will review it today @lock9 , sorry for the delay!

2020-12-10 17:20 UTC, shargon commented on src/TestEngine/TestUtils/TestConsensusContext.cs
> +        public Block CreateBlock()
@lock9 could you give me write rights? 
```suggestion
        public new Block CreateBlock()
```

2020-12-10 17:20 UTC, shargon commented on src/TestEngine/TestUtils/TestConsensusContext.cs
> +
Remove this line

2020-12-10 17:20 UTC, shargon commented on src/TestEngine/TestUtils/TestAccount.cs
> +            this.key = new KeyPair(this.privateKey);
If we use `privKey`, we could compute the `scriptHash`

2020-12-10 17:20 UTC, shargon commented on src/TestEngine/TestEngine.csproj
> +    <PackageReference Include="Neo" Version="3.0.0-CI01068" />
use `Directory.Build.props`

2020-12-10 17:20 UTC, shargon commented on src/TestEngine/Program.cs
> +                    // if something went wrong while reading the json, inserts null in this argument position
Ping

2020-12-10 17:20 UTC, shargon commented on src/TestEngine/Helper.cs
> +            return storageMap.ToJson()["value"];
I need to fix some things in order to compile.

2020-12-10 17:20 UTC, shargon commented on src/TestEngine/Engine.cs
> +            while (blocks.MoveNext())
Last()?

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Program.cs
> +                {
return BuildJsonException?

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Neo.TestEngine.csproj
> +    <PackageReference Include="Neo" Version="3.0.0-CI01089" />
use `Directory.Build.props` ?

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Engine.cs
> +        {
There are syscalls that you need to add the block in `header_index`

https://github.com/neo-project/neo-devpack-dotnet/pull/402/files#diff-c4239b07f5418a34202148d9059b032e145931f5836768413351796fb761a437R60

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Engine.cs
> +            currentTx.NetworkFee += size * NativeContract.Policy.GetFeePerByte(engine.Snapshot);
We should use `Wallet` object to compute the fee

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +            json["scriptHash"] = notification.ScriptHash.ToString();
`scripthash`

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +            json["eventName"] = notification.EventName;
`eventname`

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +            json["result_stack"] = testEngine.ResultStack.ToJson();
We agreed to use lowercase without separators for jsons.

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +        public static ScriptBuilder EmitAppCall(this ScriptBuilder sb, UInt160 scriptHash, string operation, params ContractParameter[] args)
We need to replicate this logic?

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +        public static ScriptBuilder EmitPush(this ScriptBuilder sb, ContractParameter parameter)
Same here

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/SmartContractTest.cs
> +        public string nefPath;
readonly?

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/SmartContractTest.cs
> +        public string methodName;
readonly?

2020-12-13 11:42 UTC, shargon commented on src/Neo.TestEngine/TestUtils/TestAccount.cs
> +            this.key = new KeyPair(this.privateKey);
If we provide the privatekey, it's easier to compute the public key, user can put a wrong one

2020-12-15 21:06 UTC, meevee98 commented on src/Neo.TestEngine/Helper.cs
> +        public static ScriptBuilder EmitPush(this ScriptBuilder sb, ContractParameter parameter)
I duplicated because in ``Neo.VM.Helper`` there isn't the conversion of Map values.
That was updated in [neo#2145](https://github.com/neo-project/neo/pull/2145). When the Neo version for this project is updated, this dup won't be a need anymore

2020-12-15 21:10 UTC, meevee98 commented on src/Neo.TestEngine/Helper.cs
> +        public static ScriptBuilder EmitPush(this ScriptBuilder sb, ContractParameter parameter)
actually, it didn't
``ContractParameterType.Map`` still goes to switch case's default, where it throws a ``ArgumentException``

2020-12-15 23:42 UTC, lock9 commented on src/Neo.TestEngine/Helper.cs
> +        public static ScriptBuilder EmitPush(this ScriptBuilder sb, ContractParameter parameter)
@shargon
Relates to https://github.com/neo-project/neo/pull/2145

2020-12-21 08:58 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +        public static ScriptBuilder EmitPush(this ScriptBuilder sb, ContractParameter parameter)
Done

2021-01-07 19:22 UTC, meevee98 commented on src/Neo.TestEngine/Helper.cs
> +        public static ScriptBuilder EmitPush(this ScriptBuilder sb, ContractParameter parameter)
moved to Neo.VM.Helper in https://github.com/neo-project/neo/pull/2206
when it's approved, I can remove this

2021-01-20 15:49 UTC, shargon commented on src/Neo.TestEngine/Extensions/TestExtensions.cs
> +            var key = new KeyBuilder(-1, 8).Add(contract.Hash);
In line 17 it use 0 as Id, we should use `Neo.LedgerContract.Id`

2021-02-03 09:43 UTC, shargon commented on src/Neo.Compiler.MSIL/FuncExport.cs
> +                        return "InteropInterface";
Why this changes appear?

2021-02-03 14:27 UTC, meevee98 commented on src/Neo.Compiler.MSIL/FuncExport.cs
> +                        return "InteropInterface";
this was probably a mistake when merging the master branch
it is outdated though

2021-04-29 01:15 UTC, erikzhang commented
Can anyone review it?

2021-04-30 19:11 UTC, lock9 commented
@shargon

2021-05-01 22:18 UTC, shargon commented
> This branch is out-of-date with the base branch

@lock9  Could you rebase the branch?

2021-05-04 07:20 UTC, shargon commented on tests/Neo.TestEngine.UnitTests/UnitTest_Notification.cs
> +            Directory.SetCurrentDirectory(path);
We should restore the current directory after this test, or we can produce unexpected errors in the future

2021-05-04 07:20 UTC, shargon commented on tests/Neo.TestEngine.UnitTests/UnitTest_Invoke.cs
> +            Directory.SetCurrentDirectory(path);
Same here (in all of them)

2021-05-04 07:24 UTC, shargon commented on tests/Neo.Compiler.CSharp.UnitTests/TestClasses/Contract1.cs
> +namespace Neo.Compiler.CSharp.UnitTests.TestClasses
`LF` instead of `CRLF`?

2021-05-04 07:31 UTC, shargon commented on src/Neo.TestEngine/Engine.cs
> +        public void SetEntryScript(UInt160 contractHash)
Return `this` in order to concat multiple initializations?

2021-05-06 07:13 UTC, shargon commented on src/Neo.TestEngine/Engine.cs
> +        public Engine SetEntryScript(UInt160 contractHash)
I mean in all of them too

2021-05-12 22:14 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +            json["result_stack"] = testEngine.ResultStack.ToJson();
Ping

2021-05-12 23:04 UTC, lock9 commented
@shargon 🚁

2021-05-13 07:41 UTC, shargon commented
@lock9 There are a lot of comments pending to respond like this https://github.com/neo-project/neo-devpack-dotnet/pull/365#discussion_r506929239

2021-05-13 07:43 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +        public static ScriptBuilder EmitPush(this ScriptBuilder sb, ContractParameter parameter)
It's merged now

2021-05-14 10:17 UTC, shargon commented
@lock9 could you give me edit rights?

2021-05-27 07:10 UTC, shargon commented on src/Neo.TestEngine/Helper.cs
> +            JObject json = new JObject();
Why not use `tx.ToJson()`?

2021-05-27 07:19 UTC, shargon commented on src/Neo.TestEngine/TestUtils/TestEngine.cs
> +            ExecuteTestCaseStandard(0, (ushort)rvcount, mockedNef, new StackItem[0]);
There are some unused vars in this method

2021-05-27 07:31 UTC, shargon commented on src/Neo.TestEngine/Program.cs
> +                if (json.ContainsProperty("signerAccounts") && json["signerAccounts"] is JArray accounts)
`signeraccounts`

2021-05-27 07:31 UTC, shargon commented on src/Neo.TestEngine/Program.cs
> +            if (!result.ContainsProperty("vm_state"))
without `_`

2021-05-30 11:54 UTC, shargon commented
@superboyiii could you test it?

2021-10-14 18:58 UTC, lock9 commented
Hello. It has been more than a year that this is open. Do you guys prefer that we fork this repository? Do you guys need help?

2021-11-30 21:41 UTC, devhawk commented
FYI, NGD Enterprise is working on a similar project that is integrated into the blockchain toolkit: https://github.com/ngdenterprise/neo-test/tree/devhawk/test-runner

2022-07-08 17:05 UTC, devhawk requested changes
Why are we continuing to make updates to this PR instead of https://github.com/ngdenterprise/neo-test/tree/main/src/runner

2022-12-14 17:57 UTC, closed without merging