Allow dynamic array with length
neo-project/neo-devpack-dotnet pull request #384
Opened 2020-10-28 18:31 UTC by shargon

Close https://github.com/neo-project/neo-devpack-dotnet/issues/383

2020-10-29 07:08 UTC, lightszero requested changes
but byte array is not a Array in NEOVM.

2020-11-14 12:04 UTC, shargon commented
@lightszero please, could you review it again?

2020-11-16 07:43 UTC, lightszero commented
good job,I will test this.

2020-11-20 04:35 UTC, lightszero approved these changes

2020-11-20 09:25 UTC, merged