Sync update with neo pull 2119
neo-project/neo-devpack-dotnet pull request #402
Opened 2020-12-07 06:44 UTC by chenzhitong

2020-12-07 06:46 UTC, chenzhitong commented
Need to test in conjunction with https://github.com/neo-project/neo/pull/2119/

2020-12-07 07:59 UTC, ProDog commented on src/Neo.SmartContract.Framework/Services/Neo/Contract.cs
> +        public static extern object CallNative(string name);
How to call it in the contract?😅

2020-12-07 08:04 UTC, Tommo-L commented on src/Neo.SmartContract.Framework/Services/Neo/Contract.cs
> +        public static extern object CallNative(string name);
Remove this method, it's not for normal contract.

2020-12-07 08:05 UTC, Tommo-L commented on src/Neo.SmartContract.Framework/Services/Neo/Contract.cs
> -        public static extern void Update(byte[] script, string manifest);
Add `ManagementContract` contract.

2020-12-07 08:06 UTC, ProDog commented on src/Neo.SmartContract.Framework/Services/Neo/Contract.cs
> +        public static extern object CallNative(string name);
Need to support `Update` and `Destroy`.

2020-12-07 08:23 UTC, ProDog commented
According to neo-project/neo#2119, new native contract hash is:
```
NEO hash: 0x74c21a1ca66b7a190bf2a65db83ba6fe550cea64
GAS hash: 0xb399c051778cf37a1e4ef88509b2e054d0420a32
ManagementContract hash: 0xdf18cb2476964c241558ed1e2e8881dcd2d50bde
```

2020-12-08 06:59 UTC, Tommo-L commented on src/Neo.SmartContract.Framework/Services/Neo/GAS.cs
> +        public static extern uint ActiveBlockIndex { get; }
Remove this two methods, which weren't defined for contract.

2020-12-08 07:10 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Services/Neo/GAS.cs
> +        public static extern uint ActiveBlockIndex { get; }
If you remove these fields, the fifth field will become the third one, which will be incorrect.

2020-12-08 08:01 UTC, superboyiii commented on templates/Template.CSharp/Contract1.cs
> +        Contract.Call(ManagementContract.Hash, "update", nefFile, manifest);
```suggestion
        Contract.Call(ManagementContract.Hash, "update", new object[] { nefFile, manifest });
```

2020-12-08 08:06 UTC, superboyiii commented on templates/Template.CSharp/Contract1.cs
> +        Contract.Call(ManagementContract.Hash, "destroy");
```suggestion
        Contract.Call(ManagementContract.Hash, "destroy", new object[] {});
```

2020-12-08 08:15 UTC, superboyiii requested changes

2020-12-08 08:15 UTC, superboyiii commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_CreateAndUpdate.cs
> +            Contract.Call(ManagementContract.Hash, "update", nefFile, manifest);
```suggestion
            Contract.Call(ManagementContract.Hash, "update", new object[] { nefFile, manifest });
```

2020-12-08 09:39 UTC, shargon commented
Wait for https://github.com/neo-project/neo-devpack-dotnet/pull/391

2020-12-09 05:19 UTC, cloud8little commented on src/Neo.SmartContract.Framework/Services/Neo/ManagementContract.cs
> +    class ManagementContract
should be public

2020-12-10 10:02 UTC, shargon commented on src/Neo.SmartContract.Framework/Services/Neo/GAS.cs
> +        public static extern uint ActiveBlockIndex { get; }
It can be private

2020-12-10 10:03 UTC, shargon commented on src/Neo.SmartContract.Framework/Services/Neo/GAS.cs
> +        public static extern uint ActiveBlockIndex { get; }
But ActiveBlockIndex was no exported

2020-12-10 17:01 UTC, shargon commented on src/Neo.SmartContract.Framework/Services/Neo/GAS.cs
> +        public static extern uint ActiveBlockIndex { get; }
We can use `private`

2020-12-13 11:33 UTC, shargon commented
Merge?

2020-12-13 11:33 UTC, shargon submitted a review, later dismissed

2020-12-14 07:50 UTC, superboyiii commented
I found native hash was changed again in the latest neo master.
```
NEO hash: 0x0a46e2e37c9987f570b4af253fb77e7eef0f72b6
GAS hash: 0xa6a6c15dcdc9b997dac448b6926522d22efeedfb
```
Do you think it's good to be fixed in this PR or create another? @chenzhitong @shargon

2020-12-14 08:58 UTC, shargon submitted a review, later dismissed

2020-12-14 09:13 UTC, shargon commented on src/Neo.SmartContract.Framework/Services/Neo/GAS.cs
> +        public static extern uint ActiveBlockIndex { get; }
I tested without `ActiveBlockIndex` and it works well, I think that we should remove it

2020-12-14 09:15 UTC, shargon submitted a review, later dismissed

2020-12-15 06:01 UTC, superboyiii commented
Merge?

2020-12-15 08:15 UTC, shargon submitted a review, later dismissed

2020-12-16 02:14 UTC, superboyiii commented
@erikzhang Could you review this?

2020-12-16 05:23 UTC, erikzhang approved these changes

2020-12-16 08:47 UTC, shargon approved these changes

2020-12-16 08:47 UTC, merged