Neo.Compiler.CSharp
neo-project/neo-devpack-dotnet pull request #482
Opened 2021-03-24 06:27 UTC by erikzhang

Compile directly from C# code.

- Supports more language features.
- Deterministic compilation.
- The code is more readable.
- Generates optimized code.

2021-03-24 11:19 UTC, cloud8little commented
I tried with following error, try to compile an oracle demo contract.

![6d3e0ab24fb0a1b002b19bb60239ab8](https://user-images.githubusercontent.com/34291844/112302090-a3440a00-8cd5-11eb-97f1-b1f864d17af3.png)

2021-03-24 11:59 UTC, erikzhang commented
@cloud8little Try it again? You need to update the source code for the latest `Neo.SmartContract.Framework`.

2021-03-24 18:41 UTC, devhawk commented
@erikzhang is this PR compatible with the rest of RC1? I'll be happy to try this out against my sample RC1 contract projects

2021-03-24 21:40 UTC, devhawk commented on src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
> +    <AssemblyName>nccs</AssemblyName>
low priority: I like the name nccs, but the PackageId should be explicitly specified with a neo prefix (maybe Neo.ncss) to match the rest of the neo project.

2021-03-24 21:41 UTC, devhawk commented on src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
> +    <OutputType>Exe</OutputType>
Neo.Compiler.MSIL can be compiled as a library or a dotnet tool. Does Neo.Compiler.CSharp also need to be available as a library?

2021-03-24 21:44 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +                ShowUsage();
Consider using a command line parser library. neo express uses https://github.com/natemcmaster/CommandLineUtils but there is also now an official MSFT command line parsing library to consider https://github.com/dotnet/command-line-api

2021-03-24 21:46 UTC, devhawk commented
Compiling https://github.com/devhawk/neo-registrar-sample with nccs failed

``` shell
$ nccs .\registrar.csproj
Unhandled exception. System.NotSupportedException: Unsupported symbol:
   at Neo.Compiler.MethodConvert.ConvertInvocationExpression(CompilationContext context, SemanticModel model, InvocationExpressionSyntax expression) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1131     
   at Neo.Compiler.MethodConvert.ConvertExpression(CompilationContext context, SemanticModel model, ExpressionSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 661
   at Neo.Compiler.MethodConvert.ConvertLocalDeclarationStatement(CompilationContext context, SemanticModel model, LocalDeclarationStatementSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 499
   at Neo.Compiler.MethodConvert.ConvertStatement(CompilationContext context, SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 284
   at Neo.Compiler.MethodConvert.ConvertBlockStatement(CompilationContext context, SemanticModel model, BlockSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 312
   at Neo.Compiler.MethodConvert.ConvertStatement(CompilationContext context, SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 255
   at Neo.Compiler.MethodConvert.ConvertSource(CompilationContext context, SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 231
   at Neo.Compiler.MethodConvert.Convert(CompilationContext context, SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 78
   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 210
   at Neo.Compiler.MethodConvert.Call(CompilationContext context, SemanticModel model, IMethodSymbol methodSymbol, ExpressionSyntax instanceExpression, SyntaxNode[] arguments) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1974
   at Neo.Compiler.MethodConvert.ConvertMethodInvocationExpression(CompilationContext context, SemanticModel model, IMethodSymbol symbol, ExpressionSyntax expression, ArgumentSyntax[] arguments) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1153
   at Neo.Compiler.MethodConvert.ConvertInvocationExpression(CompilationContext context, SemanticModel model, InvocationExpressionSyntax expression) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1128
   at Neo.Compiler.MethodConvert.ConvertExpression(CompilationContext context, SemanticModel model, ExpressionSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 661
   at Neo.Compiler.MethodConvert.ConvertLocalDeclarationStatement(CompilationContext context, SemanticModel model, LocalDeclarationStatementSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 499
   at Neo.Compiler.MethodConvert.ConvertStatement(CompilationContext context, SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 284
   at Neo.Compiler.MethodConvert.ConvertBlockStatement(CompilationContext context, SemanticModel model, BlockSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 312
   at Neo.Compiler.MethodConvert.ConvertStatement(CompilationContext context, SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 255
   at Neo.Compiler.MethodConvert.ConvertSource(CompilationContext context, SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 231
   at Neo.Compiler.MethodConvert.Convert(CompilationContext context, SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 78
   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 210
   at Neo.Compiler.CompilationContext.ProcessMethod(SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 201
   at Neo.Compiler.CompilationContext.ProcessClass(SemanticModel model, INamedTypeSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 177
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 140
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 137
   at Neo.Compiler.CompilationContext.ProcessCompilationUnit(SemanticModel model, CompilationUnitSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 128
   at Neo.Compiler.CompilationContext..ctor(CSharpCompilation compilation) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 39
   at Neo.Compiler.CompilationContext.Compile(String[] sourceFiles) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 78
   at Neo.Compiler.Program.ProcessSources(String folder, String[] sourceFiles) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\Program.cs:line 58
   at Neo.Compiler.Program.ProcessDirectory(String path) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\Program.cs:line 51
   at Neo.Compiler.Program.Main(String[] args) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\Program.cs:line 26
```

2021-03-25 03:52 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
> +    <OutputType>Exe</OutputType>
There is currently no such demand. In the future, if necessary, we can support it again.

2021-03-25 03:58 UTC, erikzhang commented
> I assume nccs also requires the version of Neo.SmartContract.Framework from this PR, right? However, I got the same error after I built a local copy of Neo.SmartContract.Framework from this PR and updated the package reference in the sample

@devhawk I can compile it correctly after doing this.

2021-03-25 04:55 UTC, devhawk commented
> @devhawk I can compile it correctly after doing this.
 
I was unable to. Also, since the Smart Contract framework is compiled into nccs + nccs doesn't compile the C# contract to a managed dll, I don't think it matters if I set the correct version of smart contract framework in the .csproj file. nccs doesn't even read the csproj file, does it?

2021-03-25 05:24 UTC, erikzhang commented
It doesn't read the csproj file. But the source code should be updated because the namespace of some classes has changed in the new `Smart.Contract.Framework`.

2021-03-25 05:38 UTC, devhawk commented
> It doesn't read the csproj file. But the source code should be updated because the namespace of some classes has changed in the new `Smart.Contract.Framework`.

I'll take a look in the morning (my time). We need a better error message for scenarios like this - esp. if we're changing namespaces for existing APIs

2021-03-25 09:31 UTC, cloud8little commented
Test with ec05708d5a3881dca924fd91a0c1e258dd0fce9e, compile and deploy succeed, invoke failed. 

![22e11960d52b924613d77ac3e25f2c4](https://user-images.githubusercontent.com/34291844/112450789-b7e4d880-8d8f-11eb-9da3-ba5de3dfa51a.png)

It's "INITSLOT" execution error, no data pop out from currentcontext evaluationStack.

2021-03-25 10:17 UTC, erikzhang commented
> It's "INITSLOT" execution error, no data pop out from currentcontext evaluationStack.

Fixed!

2021-03-25 11:07 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +                ShowUsage();
Done.

2021-03-25 11:36 UTC, cloud8little commented
Deploy failed.

![f76f0afcb46f190fcd28a58dab5987d](https://user-images.githubusercontent.com/34291844/112466799-36964180-8da1-11eb-88b7-1725de88a8f6.png)


```
at Neo.SmartContract.ContractTaskAwaiter.GetResult() in D:\Github\neo\src\neo\SmartContract\ContractTaskAwaiter.cs:line 18
   at Neo.SmartContract.Native.NativeContract.<Invoke>d__55.MoveNext() in D:\Github\neo\src\neo\SmartContract\Native\NativeContract.cs:line 204
```

2021-03-25 12:45 UTC, erikzhang commented
> Deploy failed.

Fixed!

2021-03-25 15:41 UTC, shargon commented
I need more days in order to review it, please wait for it

2021-03-25 16:21 UTC, devhawk commented
@erikzhang what is the plan/expectation around shared libraries?

2021-03-25 16:25 UTC, devhawk commented
Still not working with my [registrar sample](https://github.com/devhawk/neo-registrar-sample).

I built and installed nccs as a global tool:

``` shell
$ dotnet pack -o out .\src\Neo.Compiler.CSharp\
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\harry\Source\neo\official\devpack\src\Neo.SmartContract.Framework\Neo.SmartContract.Framework.csproj (in 50 ms).
  Restored C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\Neo.Compiler.CSharp.csproj (in 172 ms).
  Neo.SmartContract.Framework -> C:\Users\harry\Source\neo\official\devpack\src\Neo.SmartContract.Framework\bin\Debug\net5.0\Neo.SmartContract.Framework.dll
  Neo.Compiler.CSharp -> C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\bin\Debug\net5.0\nccs.dll
  Neo.Compiler.CSharp -> C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\bin\Debug\net5.0\nccs.dll
  Successfully created package 'C:\Users\harry\Source\neo\official\devpack\out\Neo.Compiler.CSharp.3.0.0-rc1.nupkg'.
$ dotnet tool install -g neo.compiler.csharp --add-source .\out\ --version 3.0.0-rc1
You can invoke the tool using the following command: nccs
Tool 'neo.compiler.csharp' (version '3.0.0-rc1') was successfully installed.
```

Then I changed to my local registrar sample repo's src directory

``` shell
$ nccs .\Registrar.cs
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: Unsupported symbol:
   at Neo.Compiler.MethodConvert.ConvertInvocationExpression(CompilationContext context, SemanticModel model, InvocationExpressionSyntax expression) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1186
   at Neo.Compiler.MethodConvert.ConvertExpression(CompilationContext context, SemanticModel model, ExpressionSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 685
   at Neo.Compiler.MethodConvert.ConvertLocalDeclarationStatement(CompilationContext context, SemanticModel model, LocalDeclarationStatementSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 523
   at Neo.Compiler.MethodConvert.ConvertStatement(CompilationContext context, SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 308
   at Neo.Compiler.MethodConvert.ConvertBlockStatement(CompilationContext context, SemanticModel model, BlockSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 336
   at Neo.Compiler.MethodConvert.ConvertStatement(CompilationContext context, SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 279
   at Neo.Compiler.MethodConvert.ConvertSource(CompilationContext context, SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 255
   at Neo.Compiler.MethodConvert.Convert(CompilationContext context, SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 80
   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 217
   at Neo.Compiler.MethodConvert.Call(CompilationContext context, SemanticModel model, IMethodSymbol symbol, ExpressionSyntax instanceExpression, SyntaxNode[] arguments) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2032
   at Neo.Compiler.MethodConvert.ConvertMethodInvocationExpression(CompilationContext context, SemanticModel model, IMethodSymbol symbol, ExpressionSyntax expression, ArgumentSyntax[] arguments) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1208
   at Neo.Compiler.MethodConvert.ConvertInvocationExpression(CompilationContext context, SemanticModel model, InvocationExpressionSyntax expression) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1183
   at Neo.Compiler.MethodConvert.ConvertExpression(CompilationContext context, SemanticModel model, ExpressionSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 685
   at Neo.Compiler.MethodConvert.ConvertLocalDeclarationStatement(CompilationContext context, SemanticModel model, LocalDeclarationStatementSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 523
   at Neo.Compiler.MethodConvert.ConvertStatement(CompilationContext context, SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 308
   at Neo.Compiler.MethodConvert.ConvertBlockStatement(CompilationContext context, SemanticModel model, BlockSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 336
   at Neo.Compiler.MethodConvert.ConvertStatement(CompilationContext context, SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 279
   at Neo.Compiler.MethodConvert.ConvertSource(CompilationContext context, SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 255
   at Neo.Compiler.MethodConvert.Convert(CompilationContext context, SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 80
   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 217
   at Neo.Compiler.CompilationContext.ProcessMethod(SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 206
   at Neo.Compiler.CompilationContext.ProcessClass(SemanticModel model, INamedTypeSymbol symbol) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 182
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 143
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 140
   at Neo.Compiler.CompilationContext.ProcessCompilationUnit(SemanticModel model, CompilationUnitSyntax syntax) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 131
   at Neo.Compiler.CompilationContext..ctor(Compilation compilation) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 41
   at Neo.Compiler.CompilationContext.Compile(String[] sourceFiles) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 81
   at Neo.Compiler.Program.ProcessSources(String folder, String[] sourceFiles) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\Program.cs:line 60
   at Neo.Compiler.Program.Handle(String path) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\Program.cs:line 30
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig [...]

2021-03-25 16:40 UTC, erikzhang commented
@devhawk I've modified the source code of Registrar.cs. Can you test it again?

```c#
using Neo;
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services;
using System.ComponentModel;

namespace DevHawk.Contracts
{
    [DisplayName("DevHawk.Registrar")]
    [ManifestExtra("Author", "Harry Pierson")]
    [ManifestExtra("Email", "harrypierson@hotmail.com")]
    [ManifestExtra("Description", "This is an example contract")]
    public class Registrar : SmartContract
    {
        static UInt160 GetDomainOwner(string domain)
        {
            var value = Storage.Get(Storage.CurrentContext, domain);
            return (value == null) ? UInt160.Zero : (UInt160)value;
        }

        public static UInt160 Query(string domain)
        {
            var currentOwner = GetDomainOwner(domain);
            if (currentOwner.IsZero)
            {
                Runtime.Log("Domain not registered");
            }

            return currentOwner;
        }

        public static bool Register(string domain, UInt160 owner)
        {
            var currentOwner = GetDomainOwner(domain);
            if (!currentOwner.IsZero)
            {
                Runtime.Log("Domain already registered");
                return false;
            }
            if (!Runtime.CheckWitness(owner))
            {
                Runtime.Log("CheckWitness Failed");
                return false;
            }

            Storage.Put(Storage.CurrentContext, domain, (ByteString)owner);
            return true;
        }

        public static bool Transfer(string domain, UInt160 to)
        {
            var currentOwner = GetDomainOwner(domain);
            if (currentOwner.IsZero)
            {
                Runtime.Log("Domain not registered");
                return false;
            }
            if (!Runtime.CheckWitness(currentOwner))
            {
                Runtime.Log("CheckWitness failed for current owner");
                return false;
            }
            if (!Runtime.CheckWitness(to))
            {
                Runtime.Log("CheckWitness failed for receiver");
                return false;
            }

            Storage.Put(Storage.CurrentContext, domain, (ByteString)to);
            return true;
        }

        public static bool Delete(string domain)
        {
            var currentOwner = GetDomainOwner(domain);
            if (currentOwner.IsZero)
            {
                Runtime.Log("Domain not registered");
                return false;
            }
            if (!Runtime.CheckWitness(currentOwner))
            {
                Runtime.Log("CheckWitness failed for current owner");
                return false;
            }

            Storage.Delete(Storage.CurrentContext, domain);
            return true;
        }
    }
}
```

2021-03-25 16:41 UTC, erikzhang commented
[DevHawk.Registrar.zip](https://github.com/neo-project/neo-devpack-dotnet/files/6206372/DevHawk.Registrar.zip)

This is the output of the registrar sample.

2021-03-25 16:50 UTC, devhawk commented
> @devhawk I've modified the source code of Registrar.cs. Can you test it again?

Sorry, forgot about the namespace change. Yes, changing `Neo.SmartContract.Framework.Services.Neo` to `Neo.SmartContract.Framework.Services` allowed me to compile registrar.cs.

2021-03-25 16:52 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
missing code to generate debug info

2021-03-25 16:56 UTC, devhawk commented
The compiler needs better error reporting. In particular, the user needs to be able to distinguish between invalid C# code (i.e. the `CSharpCompilation.Create` step fails) and invalid Smart Contract code (i.e. the `CSharpCompilation.Create` succeeds but the code includes operations that cannot be translated into neo vm instructions)

2021-03-25 17:00 UTC, devhawk commented
> > @devhawk I've modified the source code of Registrar.cs. Can you test it again?
> 
> Sorry, forgot about the namespace change. Yes, changing `Neo.SmartContract.Framework.Services.Neo` to `Neo.SmartContract.Framework.Services` allowed me to compile registrar.cs.

I prefer *not* having Neo twice in the namespace, but this will break almost all RC1 contracts. Is it worth it?

2021-03-25 17:01 UTC, devhawk commented
What is the plan for the MSIL based compiler? Are we planning to support both MSIL and C# based compilers? Will C# Neo dApp developers have the choice of which compiler to use? Obviously, if both are supported they both need to work on the identical source code. Will the MSIL based compiler still be able to compile the registrar contract with the updated namespace?

2021-03-25 17:06 UTC, erikzhang commented
I think the MSIL based compiler should be deprecated.

2021-03-25 17:08 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
Can you send me the document?

2021-03-25 17:14 UTC, devhawk commented
> I think the MSIL based compiler should be deprecated.

Seems a little late in the development cycle for a change like that. What would be the timeframe for deprecation?

2021-03-25 17:19 UTC, devhawk commented
To have a good developer experience for .NET, we are still going to need things like .csproj files, package references to the smart contract framework, support for dotnet restore and build to MSIL. Things like IDE errors, code completion, etc all depend on those artifacts being available.

we can also choose to have final contract compilation be C# -> NEF, but that will not eliminate the need to have C# -> MSIL as well

2021-03-25 17:22 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN11%20-%20NEO%20Debug%20Info%20Specification.md

2021-03-25 17:26 UTC, devhawk commented
At a minimum, need to port existing MSIL compiler tests to test the C# compiler

2021-03-25 18:18 UTC, devhawk commented
> I think the MSIL based compiler should be deprecated.

Are we also going to build Neo.Compiler.VisualBasic?

2021-03-25 21:55 UTC, erikzhang commented
> Are we also going to build Neo.Compiler.VisualBasic?

No. I think we will focus on c#.

2021-03-26 07:33 UTC, erikzhang commented
> To have a good developer experience for .NET, we are still going to need things like .csproj files, package references to the smart contract framework, support for dotnet restore

Done.

> build to MSIL

I don't think it's necessary.

> Things like IDE errors, code completion, etc all depend on those artifacts being available.

They are all available with the vs project template.

2021-03-26 08:13 UTC, cloud8little commented
Several questions:
1. String.ToScriptHash seems is not supported, how can I convert a address string to UInt160?
2. IsStandard() not exist any more, it is used to determine whether an address is an standard address.
3. If there is already bin/src/xxx.nef file, and without updating the display name, no new nef/manifest file will be generated.
4. use this contract project file, nef file generated successfully, but deploy failed. (https://github.com/cloud8little/examples/tree/test482/csharp/NEP17) 

error happens when deal with "CAT" opcode.

![0d901abe540a8030a3a899833e52dd2](https://user-images.githubusercontent.com/34291844/112601894-f640cd00-8e4d-11eb-95e4-e0793dd1121d.png)

![e7176f49a58662b5fea4cef62efaf9c](https://user-images.githubusercontent.com/34291844/112601901-f8a32700-8e4d-11eb-8ee3-4ebd04c8bc92.png)

5. Why use the display name as the nef file name?

2021-03-26 09:10 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
@devhawk A question: `start-address`, `end-address`, `start-line`, `end-line`, `start-column`, `end-column`, are they inclusive or not?

2021-03-26 09:16 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
And, for `sequence-points`, what if there is no document for a method? For example, the anonymous method generated from the framework.

2021-03-26 09:49 UTC, erikzhang commented
@cloud8little 

> String.ToScriptHash seems is not supported

Use `InitialValue`.

https://github.com/neo-project/neo-devpack-dotnet/blob/bfda33005f9ffc5b6995c372be0f083bd79bec2c/src/Neo.SmartContract.Framework/InitialValueAttribute.cs#L6

> If there is already bin/src/xxx.nef file, and without updating the display name, no new nef/manifest file will be generated.

They are overwritten.

> Why use the display name as the nef file name?

Because it is the contract name.

2021-03-26 10:03 UTC, Qiao-Jin commented on src/Neo.SmartContract.Framework/Helper.cs
> -        public extern static byte[] HexToBytes(this string hex, bool reverse = false);
Is there a substitution for this one?

2021-03-26 10:15 UTC, Qiao-Jin commented on src/Neo.SmartContract.Framework/SmartContract.cs
> -        public static ByteString Hash160(ByteString value)
And these 2

2021-03-26 10:35 UTC, cloud8little commented
5. Seems  Func not supported yet. delegate contract generate nef file failed. https://github.com/neo-project/neo-devpack-dotnet/blob/master/tests/Neo.Compiler.MSIL.UnitTests/TestClasses/Contract_Delegate.cs  

![a1bdeba48ae6e9de0dd41fd98558650](https://user-images.githubusercontent.com/34291844/112619111-e337f800-8e61-11eb-8a2f-b32e9f5b94db.png)

note. I will continue to build the UT contract and paste the result here.

2021-03-26 12:12 UTC, erikzhang commented
> error happens when deal with "CAT" opcode.

Fixed. Can you test it again?

> Seems Func not supported yet. delegate contract generate nef file failed.

`ToDelegate()` is obsolete. Please use `Contract.Call()`.

2021-03-26 12:12 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Helper.cs
> -        public extern static byte[] HexToBytes(this string hex, bool reverse = false);
Yes. Please use `InitialValueAttribute`.

2021-03-26 12:14 UTC, erikzhang commented on src/Neo.SmartContract.Framework/SmartContract.cs
> -        public static ByteString Hash160(ByteString value)
You have to call `CryptoLib.Sha256()` then `CryptoLib.ripemd160()`.

2021-03-26 19:26 UTC, devhawk commented
because this compiler writes its output to a different location, it breaks the [neo-test contract interface generator](https://github.com/ngdenterprise/neo-test/blob/main/README.md#contract-interface-generator). However, I took the contract interface generated against the MSIL compiler and copied it into the project and it worked - even with the old Neo.SmartContract.Framework.Services.Neo namespace

2021-03-26 19:32 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
If there is no source code document, I don't see how there can be a sequence point mapping a given instruction address to a source code document

2021-03-26 19:33 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
those values are inclusive

2021-03-26 19:37 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +using System.CommandLine;
Side note: I'd be interested in your opinion @erikzhang on this library. It didn't exist when I started development on blockchain toolkit, so I have stuck with https://github.com/natemcmaster/CommandLineUtils.

2021-03-27 02:24 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +using System.CommandLine;
I have never used CommandLineUtils, so I don't know which one is better.

2021-03-27 02:30 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
How do I map `INITSLOT` instruction to the source code document?

2021-03-27 12:15 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +            File.WriteAllBytes($"{folder}/{context.ContractName}.nef", context.CreateExecutable().ToArray());
Done.

2021-03-27 17:47 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +using System.CommandLine;
No, just wondering what you think of System.CommandLine

2021-03-27 17:50 UTC, devhawk commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +            CSharpCompilation compilation = CSharpCompilation.Create(null, syntaxTrees, references, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
Where are we checking that the compilation succeeded?

2021-03-28 03:10 UTC, lightszero commented
It is a  good start. but still can't pass  simple test.
I had add some unittest for it.

2021-03-28 03:50 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +using System.CommandLine;
I think it works well.

2021-03-28 03:53 UTC, erikzhang commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +            CSharpCompilation compilation = CSharpCompilation.Create(null, syntaxTrees, references, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
We don't need to check it. Because we will not actually generate dll.

2021-03-28 04:20 UTC, erikzhang commented
> It is a good start. but still can't pass simple test.
I had add some unittest for it.

I took a look and found that it was a test problem. I will fix the test.

2021-03-28 04:21 UTC, erikzhang commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +            if (symbol.DeclaredAccessibility != Accessibility.Public) return;
Only public class will be exported.

2021-03-28 04:38 UTC, erikzhang commented on src/Neo.Compiler.CSharp/MethodConvert.cs
> +                case "System.Numerics.BigInteger.Sqrt()":
`Sqrt` is provided in the framework.

2021-03-28 04:54 UTC, erikzhang commented
@lightszero All fixed. I added support for struct.

2021-03-28 06:22 UTC, lightszero commented
got it.we can add more test for it.

2021-03-29 08:19 UTC, Clay9910 commented
An error when invoked contract:
```
neo> invoke 0x6b7bc7bd1139c9172d6d667e917fa90f1f5ed4c0 setvalue
Invoking script with: 'wh8MCHNldHZhbHVlDBTA1F4fD6l/kX5mbS0XyTkRvcd7a0FifVtS'
VM State: FAULT
Gas Consumed: 0.0366803
Result Stack: []
Error: RVCount doesn't match with EvaluationStack
```
Contract method:
```
        public static void setvalue()
        {
            Storage.Put(Storage.CurrentContext, "test", "asdklasfd89qw");            
        }
```
It works good if I changed `void ` to other type.

2021-03-29 08:21 UTC, ProDog commented
An error when invoked contract:
```
neo> invoke 0x6b7bc7bd1139c9172d6d667e917fa90f1f5ed4c0 setvalue
Invoking script with: 'wh8MCHNldHZhbHVlDBTA1F4fD6l/kX5mbS0XyTkRvcd7a0FifVtS'
VM State: FAULT
Gas Consumed: 0.0366803
Result Stack: []
Error: RVCount doesn't match with EvaluationStack
```
Contract method:
```
        public static void setvalue()
        {
            Storage.Put(Storage.CurrentContext, "test", "asdklasfd89qw");            
        }
```
It works good if I changed `void ` to other type.

2021-03-29 09:42 UTC, erikzhang commented
All fixed!

2021-03-29 12:51 UTC, cloud8little commented
Already upload the UT, several UT was passed since last fix, please have a look into:

1. tests/Neo.Compiler.CSharp.UnitTests/UnitTest_StaticVar.cs
  Still return 7, expect 42.

2. tests/Neo.Compiler.CSharp.UnitTests/UnitTest_Types.cs
 Compile failed.

3. tests/Neo.Compiler.CSharp.UnitTests/UnitTest_MultipleContracts.cs
Compile success, expect exception.

2021-03-29 16:23 UTC, devhawk commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +            CSharpCompilation compilation = CSharpCompilation.Create(null, syntaxTrees, references, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
If the C# code that is fed into nccs is bad, how will the developer know? How will we generate valid Neo VM instructions if the C# code has errors in it?

2021-03-29 18:22 UTC, erikzhang commented
@cloud8little All fixed!

> tests/Neo.Compiler.CSharp.UnitTests/UnitTest_MultipleContracts.cs
Compile success, expect exception.

We convert the first contract and ignore the others. It is expected.

2021-03-29 21:38 UTC, shargon reviewed
> The code is more readable.

A very good move! I still reviewing the code :) too much better!

2021-03-30 05:45 UTC, Ashuaidehao commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_DebugInfo.cs
> +            //var debugInfo = testengine.ScriptEntry.debugInfo;
Can not find debug info now, is it removed?

2021-03-30 05:49 UTC, Ashuaidehao commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_FuncExport.cs
> +            //Assert.AreEqual("Null", FuncExport.ConvType(null));
"FuncExport" removed, should we remove this test?

2021-03-30 05:53 UTC, erikzhang commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_DebugInfo.cs
> +            //var debugInfo = testengine.ScriptEntry.debugInfo;
`CompilationContext.CreateDebugInformation()`.

2021-03-30 05:54 UTC, erikzhang commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_FuncExport.cs
> +            //Assert.AreEqual("Null", FuncExport.ConvType(null));
It is equivalent to `Helper.GetContractParameterType()`.

2021-03-30 06:18 UTC, Ashuaidehao commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_FuncExport.cs
> +            //Assert.AreEqual("Null", FuncExport.ConvType(null));
Cannot access "Helper" cause it's internal class.

2021-03-30 06:33 UTC, erikzhang commented on tests/Neo.Compiler.CSharp.UnitTests/UnitTest_FuncExport.cs
> +            //Assert.AreEqual("Null", FuncExport.ConvType(null));
The UT can access `internal` classes.

2021-03-30 09:33 UTC, cloud8little commented
@erikzhang Map with the byte array key was not supported before, should we still throw exception when generating nef/manifest file? 

![872be8534784b9454ee617eaa6f8fa0](https://user-images.githubusercontent.com/34291844/112966767-1d183f80-917d-11eb-8400-d0820c21c12c.png)

2021-03-30 09:40 UTC, erikzhang commented
> Map with the byte array key was not supported before, should we still throw exception when generating nef/manifest file?

This should not be the responsibility of the compiler.

2021-03-30 11:19 UTC, erikzhang commented
All UTs pass!

2021-03-30 11:49 UTC, erikzhang commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +            CSharpCompilation compilation = CSharpCompilation.Create(null, syntaxTrees, references, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
Updated. Now we check it here.

https://github.com/neo-project/neo-devpack-dotnet/blob/a6ed7cd3263422b2bfb8ad38889e60ed578646eb/src/Neo.Compiler.CSharp/CompilationContext.cs#L60-L66

2021-03-30 17:34 UTC, devhawk commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +                    throw new Exception(message);
This is a pretty awful developer experience. nccs should have a similar output when enountering an error as csc does

2021-03-30 17:35 UTC, devhawk commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +        public JObject CreateDebugInformation()
Has anyone attempted to use this output in the debugger yet?

2021-03-30 17:38 UTC, devhawk commented on src/Neo.Compiler.CSharp/Optimizer.cs
> +    static class Optimizer
Should the optimizer be split out so it can be used from other compilers?

2021-03-30 20:43 UTC, devhawk commented on src/Neo.SmartContract.Framework/ByteString.cs
> +        [OpCode(OpCode.NOP)]
Will these changes also work with the MSIL compiler?

2021-03-31 04:47 UTC, erikzhang commented on src/Neo.SmartContract.Framework/ByteString.cs
> +        [OpCode(OpCode.NOP)]
Yes. But the MSIL compiler will be removed soon.

2021-03-31 08:15 UTC, erikzhang commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +                    throw new Exception(message);
Updated.

2021-03-31 13:50 UTC, erikzhang commented
Merge?

2021-03-31 14:28 UTC, devhawk requested changes
Do not remove the MSIL based compiler in this PR

2021-03-31 14:47 UTC, erikzhang commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +            if (scTypeFound) return;
Yes.

2021-03-31 14:50 UTC, erikzhang commented
> Do not remove the MSIL based compiler in this PR

The old compiler doesn't work with the latest `Neo.SmartContract.Framework`. And we are not going to fix it because we don't have the energy to maintain multiple compilers.

2021-03-31 18:20 UTC, devhawk commented
> > Do not remove the MSIL based compiler in this PR
> 
> The old compiler doesn't work with the latest `Neo.SmartContract.Framework`. And we are not going to fix it because we don't have the energy to maintain multiple compilers.

Then we need to fork the smart contract framework so we can keep both the MSIL and C# based compilers around. Breaking everyone's RC1 tool chain in the last few months before shipping MainNet is too risky

There is a lot of [new content](https://ngdenterprise.com/neo-tutorials/) using the existing compiler. Until we can test that content with the new compiler, we need to keep the MSIL compiler around. If we made changes to the smart contract framework that breaks MSIL compiler, we need to keep the fork that works with MSIL around as well.

2021-03-31 19:12 UTC, erikzhang commented
@devhawk I've created a new branch: https://github.com/neo-project/neo-devpack-dotnet/tree/msil. And we won't keep the MSIL compiler in the master branch.

2021-03-31 19:59 UTC, devhawk commented
Is the new C# compiler RC1 compatible? Can we publish an RC1 compatible C# compiler + Smart Contract framework for C# compiler for immediate test purposes?

2021-03-31 21:59 UTC, devhawk commented
We should replace the Visual Studio based templates w/ ones that work with `dontnet new` like https://github.com/ngdenterprise/neo-templates

2021-03-31 22:03 UTC, devhawk commented
We should consider having a single Smart Contract Framework [reference assembly](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies) and move all of the compiler specific information like OpCode Attributes to the relevant compiler.

2021-03-31 22:05 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +                foreach (Diagnostic diagnostic in context.Diagnostics)
Much improved!

2021-04-01 00:20 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +                new Option<bool>(new[] { "-d", "--debug" }, "Indicates whether to generate debugging information."),
We should always produce debug info

2021-04-01 00:25 UTC, devhawk commented
`PrepareArgumentsForMethod` throws on this contract:

``` csharp
using System.ComponentModel;
using System.Numerics;
using Neo;
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services;

public class StorageContract : SmartContract
{
    static BigInteger number
    {
        get
        {
            return (BigInteger)Storage.Get(Storage.CurrentContext, nameof(number));
        }
        set
        {
            Storage.Put(Storage.CurrentContext, nameof(number), value);
        }
    }

    public static void Store(BigInteger num)
    {
        number = num;
    }

    public static BigInteger Retrieve()
    {
        return number;
    }
}
```

compiler output:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.Compiler.MethodConvert.PrepareArgumentsForMethod(SemanticModel model, IMethodSymbol symbol, IReadOnlyList`1 arguments, CallingConvention callingConvention) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 3004
   at Neo.Compiler.MethodConvert.ConvertDelegateInvocationExpression(SemanticModel model, ExpressionSyntax expression, ArgumentSyntax[] arguments) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2047  
   at Neo.Compiler.MethodConvert.ConvertInvocationExpression(SemanticModel model, InvocationExpressionSyntax expression) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2005
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 856
   at Neo.Compiler.MethodConvert.PrepareArgumentsForMethod(SemanticModel model, IMethodSymbol symbol, IReadOnlyList`1 arguments, CallingConvention callingConvention) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 3022
   at Neo.Compiler.MethodConvert.Call(SemanticModel model, IMethodSymbol symbol, ExpressionSyntax instanceExpression, SyntaxNode[] arguments) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2961       
   at Neo.Compiler.MethodConvert.ConvertMethodInvocationExpression(SemanticModel model, IMethodSymbol symbol, ExpressionSyntax expression, ArgumentSyntax[] arguments) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2032
   at Neo.Compiler.MethodConvert.ConvertInvocationExpression(SemanticModel model, InvocationExpressionSyntax expression) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2002
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 856
   at Neo.Compiler.MethodConvert.ConvertExpressionStatement(SemanticModel model, ExpressionStatementSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 476
   at Neo.Compiler.MethodConvert.ConvertStatement(SemanticModel model, StatementSyntax statement) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 377
   at Neo.Compiler.MethodConvert.ConvertBlockStatement(SemanticModel model, BlockSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 422
   at Neo.Compiler.MethodConvert.ConvertStatement(SemanticModel model, StatementSyntax statement) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 362
   at Neo.Compiler.MethodConvert.ConvertSource(SemanticModel model) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 333
   at Neo.Compiler.MethodConvert.Convert(SemanticModel model) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 112
   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 334
   at Neo.Compiler.MethodConvert.Call(SemanticModel model, IMethodSymbol symbol, CallingConvention callingConvention) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2976
   at Neo.Compiler.MethodConvert.ConvertIdentifierNameAssignment(SemanticModel model, IdentifierNameSyntax left) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1063
   at Neo.Compiler.MethodConvert.ConvertSimpleAssignmentExpression(SemanticModel model, AssignmentExpressionSyntax expression) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 984
   at Neo.Compiler.MethodConvert.ConvertAssignmentExpression(SemanticModel model, AssignmentExpressionSyntax expression) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 960
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 820
   at Neo.Compiler.MethodConvert.ConvertExpressionStatement(SemanticModel model, ExpressionStatementSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 476
   at Neo.Compiler.MethodConvert.ConvertStatement(SemanticModel model, StatementSyntax statement) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 377
   at Neo.Compiler.MethodConvert.ConvertBlockStatement(SemanticModel model, BlockSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 422
   at Neo.Compiler.MethodConvert.ConvertStatement(SemanticModel model, StatementSyntax statement) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 362
   at Neo.Compiler.MethodConvert.ConvertSource(SemanticModel model) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 349
   at Neo.Compiler.MethodConvert.Convert(SemanticModel model) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 112
   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 334
   at Neo.Compiler.CompilationContext.ProcessMethod(SemanticModel model, IMethodSymbol symbol) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 323
   at Neo.Compiler.CompilationContext.ProcessClass(SemanticModel model, INamedTypeSymbol symbol) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 294
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 255
   at Neo.Compiler.CompilationContext.ProcessCompilationUnit(SemanticModel model, CompilationUnitSyntax syntax) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 243
   at Neo.Compiler.CompilationContext.Compile() in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 67
   at Neo.Compiler.CompilationContext.Compile(String csproj, String[] sourceFiles, Options options) in c:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 130
   at Neo.Compiler.CompilationContext.CompileSources(String[] sourceFiles, Options options) in c:\Users\harry\Source\neo\official\de [...]

2021-04-01 00:49 UTC, devhawk commented
> Is the new C# compiler RC1 compatible? Can we publish an RC1 compatible C# compiler + Smart Contract framework for C# compiler for immediate test purposes?

BTW, by "RC1 compatible" I mean compiles contracts written against the existing 3.0.0-rc1 Neo.SmartContract.Framework package without any code changes (So things like Storage class need to stay in the `Neo.SmartContract.Framework.Services.Neo` namespace for the RC1 compatible version)

2021-04-01 02:14 UTC, cloud8little commented
> `PrepareArgumentsForMethod` throws on this contract. It works w/ NEON (using Neo.SmartContract.Framework.Services.Neo namespace instead of Neo.SmartContract.Framework.Services)

@erikzhang  nameof is not supported,  we should add the support for it.

2021-04-01 04:37 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Program.cs
> +                new Option<bool>(new[] { "-d", "--debug" }, "Indicates whether to generate debugging information."),
Is it bad to add an option?

2021-04-01 04:38 UTC, erikzhang commented
> The Smart Contract framework for C# compiler needs a different package name for now than the existing one that works with MSIL compiler.

We can use a different version. But I'm not going to change the package name.

> Is the new C# compiler RC1 compatible?

No. Even the old one is not compatible with RC1.

> We should replace the Visual Studio based templates w/ ones that work with dontnet new

We can do it later.

2021-04-01 05:23 UTC, erikzhang commented
> nameof is not supported, we should add the support for it.

Fixed.

2021-04-01 10:49 UTC, cloud8little commented
why it is not supported?

```cs
[InitialValue("024700db2e90d9f02c4f9fc862abaca92725f95b4fddcc8d7ffa538693ecf463a9", ContractParameterType.PublicKey)]
private static readonly ECPoint publicKey2Ecpoint = default;
```

2021-04-01 10:55 UTC, erikzhang commented
> why it is not supported?

In my local test it can be compiled. You can add a UT for it.

2021-04-01 11:37 UTC, shargon approved these changes
The code is much more readable and well structured than the previous version, a breakthrough!

2021-04-01 12:31 UTC, cloud8little commented
the Test coverage is incorrect, it counts testing code in.

2021-04-01 13:06 UTC, erikzhang commented
> the Test coverage is incorrect, it counts testing code in.

How to exclude them?

2021-04-01 13:38 UTC, erikzhang commented
I will merge it first. If there are any problems, we can improve it later.

2021-04-01 13:38 UTC, merged