Add Nep11Token base class to framework
neo-project/neo-devpack-dotnet pull request #531
Opened 2021-04-09 07:03 UTC by erikzhang

2021-04-09 09:54 UTC, shargon commented on src/Neo.SmartContract.Framework/SupportedStandardsAttribute.cs
> +    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
The argument it's an array, why multiple?

2021-04-09 11:29 UTC, erikzhang commented on src/Neo.SmartContract.Framework/SupportedStandardsAttribute.cs
> +    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
Because we may use it on both base class and sub class.

2021-04-09 12:07 UTC, shargon commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +            if (to is null) throw new ArgumentNullException(nameof(to));
```suggestion
            if (to is null || !to.IsValid) throw new ArgumentException(nameof(to));
```

2021-04-09 12:07 UTC, shargon commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +            StorageMap accountMap = new(Storage.CurrentContext, Prefix_AccountToken);
```suggestion
            if (owner is null || !owner.IsValid) throw new ArgumentException(nameof(owner));
            StorageMap accountMap = new(Storage.CurrentContext, Prefix_AccountToken);
```

2021-04-09 12:07 UTC, shargon commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +            if (owner is null) throw new Exception("Owner cannot be null.");
```suggestion
            if (owner is null || !owner.IsValid) throw new ArgumentException(nameof(owner));
```

2021-04-09 12:26 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +            if (to is null) throw new ArgumentNullException(nameof(to));
Fixed.

2021-04-09 12:27 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +            StorageMap accountMap = new(Storage.CurrentContext, Prefix_AccountToken);
Fixed.

2021-04-09 12:27 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +            if (owner is null) throw new Exception("Owner cannot be null.");
Fixed.

2021-04-09 14:17 UTC, shargon approved these changes

2021-04-10 11:34 UTC, ProDog commented
Compile error🤔:
```
error NC1002: Unknown method: Neo.SmartContract.Framework.Nep11Token<Neo.SmartContract.Framework.Nep11TokenState>.Decimals()
```

2021-04-10 13:17 UTC, erikzhang commented
Wait for #546

2021-04-10 20:45 UTC, devhawk reviewed
Can we give this a more descriptive name like `NonFungibleToken` instead of `Nep11Token1`

2021-04-11 03:06 UTC, erikzhang commented
It implements NEP-11. And I'm not sure whether we will have another NFT NEP.

2021-04-13 03:47 UTC, ProDog commented
Need merge master to this.

2021-04-13 04:10 UTC, erikzhang commented
@ProDog If you want to test it, you need to pack it to a nuget package, then refer it in the smart contract project.

2021-04-13 06:05 UTC, ProDog commented
New compile  error:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Neo.SmartContract.Framework.ByteString' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Compiler.MethodConvert.ConvertIdentifierNameExpression(SemanticModel model, IdentifierNameSyntax expression) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2439
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1129
   at Neo.Compiler.MethodConvert.PrepareArgumentsForMethod(SemanticModel model, IMethodSymbol symbol, IReadOnlyList`1 arguments, CallingConvention callingConvention) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 3735
   at Neo.Compiler.MethodConvert.Call(SemanticModel model, IMethodSymbol symbol, ExpressionSyntax instanceExpression, SyntaxNode[] arguments) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 3657
   at Neo.Compiler.MethodConvert.ConvertElementAccessExpression(SemanticModel model, ElementAccessExpressionSyntax expression) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2340
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1123
   at Neo.Compiler.MethodConvert.PrepareArgumentsForMethod(SemanticModel model, IMethodSymbol symbol, IReadOnlyList`1 arguments, CallingConvention callingConvention) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 3735
   at Neo.Compiler.MethodConvert.Call(SemanticModel model, IMethodSymbol symbol, ExpressionSyntax instanceExpression, SyntaxNode[] arguments) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 3657
   at Neo.Compiler.MethodConvert.ConvertMethodInvocationExpression(SemanticModel model, IMethodSymbol symbol, ExpressionSyntax expression, ArgumentSyntax[] arguments) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2571
   at Neo.Compiler.MethodConvert.ConvertInvocationExpression(SemanticModel model, InvocationExpressionSyntax expression) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2541
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1138
   at Neo.Compiler.MethodConvert.ConvertCastExpression(SemanticModel model, CastExpressionSyntax expression) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2077
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1114
   at Neo.Compiler.MethodConvert.ConvertLocalDeclarationStatement(SemanticModel model, LocalDeclarationStatementSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 928
   at Neo.Compiler.MethodConvert.ConvertStatement(SemanticModel model, StatementSyntax statement) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 466
   at Neo.Compiler.MethodConvert.ConvertBlockStatement(SemanticModel model, BlockSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 496
   at Neo.Compiler.MethodConvert.ConvertStatement(SemanticModel model, StatementSyntax statement) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 430
   at Neo.Compiler.MethodConvert.ConvertSource(SemanticModel model) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 417
   at Neo.Compiler.MethodConvert.Convert(SemanticModel model) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\MethodConvert.cs:line 131
   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 402
   at Neo.Compiler.CompilationContext.ProcessMethod(SemanticModel model, IMethodSymbol symbol, Boolean export) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 382
   at Neo.Compiler.CompilationContext.ProcessClass(SemanticModel model, INamedTypeSymbol symbol) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 349
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 306
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 303
   at Neo.Compiler.CompilationContext.ProcessCompilationUnit(SemanticModel model, CompilationUnitSyntax syntax) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 294
   at Neo.Compiler.CompilationContext.Compile() in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 98
   at Neo.Compiler.CompilationContext.Compile(IEnumerable`1 sourceFiles, IEnumerable`1 references, Options options) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 126
   at Neo.Compiler.CompilationContext.CompileProject(String csproj, Options options) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 183
   at Neo.Compiler.Program.ProcessCsproj(Options options, String path) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\Program.cs:line 73
   at Neo.Compiler.Program.Handle(Options options, String path) in D:\Work\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\Program.cs:line 42
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System. [...]

2021-04-13 06:53 UTC, erikzhang commented
@ProDog It should be fixed by #554

2021-04-13 07:25 UTC, ProDog commented
> @ProDog It should be fixed by #554

Yes, it compiles properly, the new question is:

I wrote a method `Mint`:
```C#
        [InitialValue("NUNtEBBbJkmPrmhiVSPN6JuM7AcE8FJ5sE", Neo.SmartContract.ContractParameterType.Hash160)]
        public static UInt160 Owner;

        public static void Mint()
        {
            ByteString tokenID = NewTokenId();
            Nep11TokenState tokenState = new Nep11TokenState() { Owner = Owner, Name = "My test token" };

            Mint(tokenID, tokenState);
        }
```
An error when invoke:
```
neo> invoke 0x1c212599f28d8bde7d4daed9c13fcc584bf4cb94 mint
Invoking script with: 'wh8MBG1pbnQMFJTL9EtYzD/B2a5Nfd6LjfKZJSEcQWJ9W1I='
VM State: FAULT
Gas Consumed: 0.0384863
Result Stack: []
Error: Specified cast is not valid.
neo>
```

2021-04-13 10:49 UTC, erikzhang commented
@ProDog Fixed!

2021-04-13 11:26 UTC, ProDog commented
`Mint` works fine, but the `balanceOf` is always `0`:
```
neo> invoke 0xe26773346a82cb2f4d21d695bd4445e079a03f87 mint [{"type":"Hash160","value":"0x4638f10d3fdc2cce2ea14625dbc1672b2919d85c"}]
Invoking script with: 'DBRc2BkpK2fB2yVGoS7OLNw/DfE4RhHAHwwEbWludAwUhz+geeBFRL2V1iFNL8uCajRzZ+JBYn1bUg=='
VM State: HALT
Gas Consumed: 0.3531302
Result Stack: [{"type":"Any"}]
Relay tx(no|yes): yes
Signed and relayed transaction with hash=0xc468c695544cb37d9ce461a272634470a74a5e7529ee4f2ae3287b025a4114e4
neo> invoke 0xe26773346a82cb2f4d21d695bd4445e079a03f87 balanceOf [{"type":"Hash160","value":"0x4638f10d3fdc2cce2ea14625dbc1672b2919d85c"}]
Invoking script with: 'DBRc2BkpK2fB2yVGoS7OLNw/DfE4RhHAHwwJYmFsYW5jZU9mDBSHP6B54EVEvZXWIU0vy4JqNHNn4kFifVtS'
VM State: HALT
Gas Consumed: 0.0278418
Result Stack: [{"type":"Integer","value":"0"}]
Relay tx(no|yes): no
neo> invoke gas balanceOf [{"type":"Hash160","value":"0x4638f10d3fdc2cce2ea14625dbc1672b2919d85c"}]
Invoking script with: 'DBRc2BkpK2fB2yVGoS7OLNw/DfE4RhHAHwwJYmFsYW5jZU9mDBTPduKL0AYsSkeO41VhARMZ88+k0kFifVtS'
VM State: HALT
Gas Consumed: 0.0202833
Result Stack: [{"type":"Integer","value":"992824251250"}]
Relay tx(no|yes): no
neo>
```

2021-04-14 02:20 UTC, ProDog commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +            if (balance.IsZero)
I found here was `true`, but the `balance` actually `1`.

2021-04-14 03:00 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +            if (balance.IsZero)
Fixed!

2021-04-14 03:42 UTC, ProDog requested changes

2021-04-14 03:42 UTC, ProDog commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +                Contract.Call(to, "onNEP11Payment", CallFlags.All, from, 1, tokenId, data);
```suggestion
                Contract.Call(to, "onNEP11Payment", CallFlags.All, new object[] { from, 1, tokenId, data });
```

2021-04-14 03:44 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +                Contract.Call(to, "onNEP11Payment", CallFlags.All, from, 1, tokenId, data);
It's not necessary.

2021-04-14 03:45 UTC, ProDog commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +                Contract.Call(to, "onNEP11Payment", CallFlags.All, from, 1, tokenId, data);
An error when transfer NFT to contract address:
```
Error: Object of type 'Neo.VM.Types.ByteString' cannot be converted to type 'Neo.VM.Types.Array'.
```

2021-04-14 03:48 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +                Contract.Call(to, "onNEP11Payment", CallFlags.All, from, 1, tokenId, data);
I think it's a compiler error. I will check it.

2021-04-14 06:35 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +                Contract.Call(to, "onNEP11Payment", CallFlags.All, from, 1, tokenId, data);
It should be fixed by #559

2021-04-14 07:22 UTC, ProDog commented on src/Neo.SmartContract.Framework/Nep11Token.cs
> +                Contract.Call(to, "onNEP11Payment", CallFlags.All, from, 1, tokenId, data);
Tested OK.

2021-04-14 10:10 UTC, shargon commented
It's full tested?

2021-04-14 10:14 UTC, ProDog commented
> It's full tested?

Yes. no other problems.

2021-04-14 10:23 UTC, shargon approved these changes

2021-04-14 11:18 UTC, merged