Improve CompilationContext.ContractName
neo-project/neo-devpack-dotnet pull request #723
Opened 2022-03-17 06:01 UTC by erikzhang

1. Revert #722
2. Fix #720

@devhawk @shargon

2022-03-17 09:10 UTC, shargon approved these changes

2022-03-17 14:26 UTC, devhawk commented
As I understand it, we can't even run the tool until #721 is fixed, right? IMO, this PR (and all PRs frankly) for devpack should wait until #721 is fixed.

2022-03-17 22:11 UTC, devhawk requested changes
The more I think about this, the more I think that it's important NOT to tie the contract name and the base name for contract/manifest/debug info files

2022-03-20 06:54 UTC, erikzhang commented
> The more I think about this, the more I think that it's important NOT to tie the contract name and the base name for contract/manifest/debug info files

The logic and behavior of this PR is the same as the current code, just easier to read.

2022-03-20 15:09 UTC, devhawk commented
> > The more I think about this, the more I think that it's important NOT to tie the contract name and the base name for contract/manifest/debug info files
> 
> The logic and behavior of this PR is the same as the current code, just easier to read.

This is not accurate. `ProcessOutputs` currently uses `options.ContractName` as the base file name if it's not null and then falls back to using `context.ContractName`. That code was replaced with code that uses `context.ContractName` as the base file name.

Build tools need a mechanism to control the file name of the generated files, without depending on the contents of any source file. At the same time, I think it's important for developers to be able to manage the names of their contracts without constraints imposed by the build tools 

Maybe we should add a separate option to specify the base name of the generated files? The .NET C# compiler uses [`-out:`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#outputassembly) argument, but that would collide with the existing `--output` NCCS compiler argument. How about `--base-name`?

2022-03-20 15:12 UTC, devhawk commented on src/Neo.Compiler.CSharp/Program.cs
> +                string path = Path.Combine(folder, $"{context.ContractName}.nef");
Using context.ContractName here forces the contract name in the manifest to be the same as the base name of the generated files.

2022-03-20 15:17 UTC, devhawk commented on src/Neo.Compiler.CSharp/CompilationContext.cs
> +        public string? ContractName => Options.ContractName ?? displayName ?? assemblyName ?? className;
This line overrides the contract name in source, re-breaking #674 and #696

2022-03-27 03:54 UTC, erikzhang commented
> Maybe we should add a separate option to specify the base name of the generated files? The .NET C# compiler uses [-out:](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#outputassembly) argument, but that would collide with the existing --output NCCS compiler argument. How about --base-name?

I think it's okay. And `--contract-name` can be removed.

2022-03-27 04:04 UTC, devhawk approved these changes

2022-03-27 04:55 UTC, merged