Sync GetTransactionSigners
neo-project/neo-devpack-dotnet pull request #731
Opened 2022-04-21 12:16 UTC by shargon

2022-04-22 06:06 UTC, erikzhang requested changes

2022-04-22 06:06 UTC, erikzhang commented on src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
> +    <PackageReference Include="Neo" Version="3.2.1-CI01335" />
We don't allow CI packages in master branch.

2022-04-22 14:21 UTC, shargon commented on src/Neo.Compiler.CSharp/Neo.Compiler.CSharp.csproj
> +    <PackageReference Include="Neo" Version="3.2.1-CI01335" />
Fixed

2022-04-22 23:51 UTC, erikzhang commented
And `GetTransactionVMState`?

2022-04-22 23:52 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Native/Ledger.cs
> +        public static extern object[] GetTransactionSigners(UInt256 hash);
Return `Signer[]` instead of `object[]`?

2022-04-26 10:49 UTC, shargon commented on src/Neo.SmartContract.Framework/Native/Ledger.cs
> +        public static extern object[] GetTransactionSigners(UInt256 hash);
Done

2022-04-26 23:28 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Native/Signer.cs
> +        public object[] Rules;
`WitnessRule`

2022-04-27 09:20 UTC, shargon commented on src/Neo.SmartContract.Framework/Native/Signer.cs
> +        public object[] Rules;
How can we convert between different types?

2022-04-27 10:09 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Native/Signer.cs
> +        public object[] Rules;
Check `WitnessRule.Type` and then convert.

2022-04-27 13:51 UTC, shargon commented on src/Neo.SmartContract.Framework/Native/Signer.cs
> +        public object[] Rules;
Done. Please, check it if do you want one file per class.

2022-04-28 08:51 UTC, Ashuaidehao commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_Blockchain.cs
> +            if (whatReturn == "Signers") return Ledger.GetTransactionSigners(tx.Hash);
Please use these code here and add several "WitnessRule"signers in test engine tx:
```csharp
 {
                var signers = Ledger.GetTransactionSigners(tx.Hash);
                foreach (var signer in signers)
                {
                    var rule = signer.Rules;
                }
                return Ledger.GetTransactionSigners(tx.Hash);
            }
```

As we test, it will throw an exception `The given key 'Neo.VM.Types.Array' was not present in the dictionary.` in **ReferenceCounter.CheckZeroReferred()**.
This may be caused by missing "ReferenceCounter" in these lines:

https://github.com/neo-project/neo/blob/ed68274e7dec2622468d3bc67df6e0f2913d903b/src/neo/Network/P2P/Payloads/Signer.cs#L194

https://github.com/neo-project/neo/blob/ed68274e7dec2622468d3bc67df6e0f2913d903b/src/neo/Network/P2P/Payloads/Signer.cs#L195

https://github.com/neo-project/neo/blob/ed68274e7dec2622468d3bc67df6e0f2913d903b/src/neo/Network/P2P/Payloads/Signer.cs#L196

2022-04-28 09:37 UTC, mialbu commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_Blockchain.cs
> +            if (whatReturn == "Signers") return Ledger.GetTransactionSigners(tx.Hash);
I can confirm this. As soon as a signer is present with witness scope `WitnessRules`, I get the same exception (`The given key 'Neo.VM.Types.Array' was not present in the dictionary.`) when trying to access a signer from the list.

I've also noticed that when only one signer with witness scope `WitnessRules` is present:
- I can access only this signer from the list, but retrieving its fields (`account`, etc.) still results in the same exception.
- Trying to access other signers from the list results in the same exception.

When more than one signers with witness scope `WitnessRules` are present, I cannot access any of the signers (same exception).

2022-04-28 11:30 UTC, erikzhang commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_Blockchain.cs
> +            if (whatReturn == "Signers") return Ledger.GetTransactionSigners(tx.Hash);
It should be fixed by neo-project/neo#2711

2022-04-29 09:25 UTC, shargon commented on src/Neo.SmartContract.Framework/Native/Signer.cs
> +        public object[] Rules;
Done

2022-04-29 10:48 UTC, erikzhang approved these changes

2022-04-29 23:16 UTC, merged