Storage backed properties
neo-project/neo-devpack-dotnet pull request #745
Opened 2022-05-09 12:02 UTC by erikzhang

Close #585

2022-05-09 20:10 UTC, devhawk requested changes
This doesn't seem worth it to me for simple, single value storage properties. 

I would *love* to see a declarative solution for contract storage. It would simplify contract development + the debugger could use up the storage declarations automatically for [storage key & item decoding](https://github.com/neo-project/neo-debugger/blob/master/docs/storage-schema-overview.md).

Instead of just solving the simplest storage problem (single value storage such as `TotalSupply`), can we instead work on an approach that would also work for:

* Single key storage maps (such as NEP 17 token balances)
* Multiple key storage maps
* Key index storages (such as NEP 11 account token storage)
* Storage Lists (i.e. storage maps w/ integer keys with List like semantics to Add/Remove items from the end)

2022-05-09 23:34 UTC, erikzhang commented on src/Neo.SmartContract.Framework/Nep17Token.cs
> +            TotalSupply += amount;
Using a compiler is inherently more expensive. This is inevitable. And the price of `System.Storage.GetContext` is only equivalent to executing `OpCode.ADD` twice, which is negligible in my opinion.

2022-05-09 23:40 UTC, erikzhang commented
>Instead of just solving the simplest storage problem (single value storage such as TotalSupply), can we instead work on an approach that would also work for:
>
>Single key storage maps (such as NEP 17 token balances)
Multiple key storage maps
Key index storages (such as NEP 11 account token storage)
Storage Lists (i.e. storage maps w/ integer keys with List like semantics to Add/Remove items from the end)

Maybe we can go step by step. I'm currently just implementing the functionality requested in #585. These complex functions you mentioned can be discussed separately by creating a new issue.

2022-05-10 07:56 UTC, shargon approved these changes

2022-05-10 09:57 UTC, vncoelho commented
Good change!

2022-05-10 09:58 UTC, vncoelho submitted a review, later dismissed

2022-05-10 15:53 UTC, devhawk commented
> Maybe we can go step by step. I'm currently just implementing the functionality requested in #585. These complex functions you mentioned can be discussed separately by creating a new issue.

Happy to file a new issue, but I don't think we should approach this "step by step". From what I've seen, the majority of contract storages are not simple single values like this. Most contract storages use `StorageMap` with one or more keys in order to store multiple values.

This PR saves the developer a couple lines of code, doesn't solve the real problem and potentially constrains our ability to deliver a complete solution in the future. Not worth it in my opinion.

2023-11-15 12:28 UTC, shargon commented on src/Neo.SmartContract.Framework/Attributes/StorageBackedAttribute.cs
> +// Copyright (C) 2015-2022 The Neo Project.
```suggestion
// Copyright (C) 2015-2023 The Neo Project.
```

2023-11-15 12:28 UTC, shargon commented on src/Neo.SmartContract.Framework/Nep11Token.cs
>          [Safe]
Using `Safe` in base class, we should check if we need to define it also here (in get)

2023-11-15 12:29 UTC, shargon commented
I think that this PR is an important one, we should work on it @Liaojinghui

2023-11-15 13:03 UTC, Liaojinghui submitted a review, later dismissed

2023-11-15 13:03 UTC, Liaojinghui commented
@shargon is this compatible to the previous code?

2023-11-15 13:18 UTC, shargon commented
> @shargon is this compatible to the previous code?

We need to check it 😅

2023-11-15 13:31 UTC, Liaojinghui commented
Since all unit test passes, it should be fine. I have approved it, you can merge when you are avilable.

2023-11-16 09:04 UTC, shargon commented
It seems that `.get` and `static` properties are not working.

2023-11-16 09:55 UTC, Liaojinghui approved these changes

2023-11-16 09:56 UTC, Liaojinghui commented
Was about to comment, misclicked approve.

2023-11-16 10:41 UTC, Liaojinghui commented
If we do it this way, it works:

```C#
       public static BigInteger getWithKey()
        {
            ValueB = value; return ValueB;
            
        }
```

if we remove ` ValueB = value;`, it fault,,,,,,even though this code does nothing.

2023-11-16 11:09 UTC, Liaojinghui commented
I can only dig this far:

`context_pop.EvaluationStack.Count != context_pop.RVCount` check fail as `EvaluationStack.Count` is 2 and `RVCount` is 1

![Screenshot 2023-11-16 at 7 08 07 PM](https://github.com/neo-project/neo-devpack-dotnet/assets/10189511/7de6dffe-5e97-41de-aa5d-53f70c40f10e)

2023-11-16 12:29 UTC, Liaojinghui commented on src/Neo.Compiler.CSharp/MethodConvert.cs
> +                AddInstruction(OpCode.DUP);
```suggestion
                // AddInstruction(OpCode.DUP);
```

2023-11-16 13:33 UTC, shargon commented
> I can only dig this far:
> 
> `context_pop.EvaluationStack.Count != context_pop.RVCount` check fail as `EvaluationStack.Count` is 2 and `RVCount` is 1
> 
> ![Screenshot 2023-11-16 at 7 08 07 PM](https://user-images.githubusercontent.com/10189511/283428783-7de6dffe-5e97-41de-aa5d-53f70c40f10e.png)

Maybe we need to remove the null before, when is static

2023-11-16 13:57 UTC, Liaojinghui commented
I will keep debug tomorrow if you haven't solved it by then. But this really makes me believe we should also add the compiler to the monorepo, i need to change reference of neo and vm to debug the issue.

2023-11-16 13:58 UTC, vncoelho commented
So move it all for now and let's see this experience.

2023-11-16 13:59 UTC, cschuchardt88 commented
@Liaojinghui  Just create your own nuget store on your computers file system

https://learn.microsoft.com/en-us/nuget/hosting-packages/local-feeds

2023-11-16 14:01 UTC, Liaojinghui commented
> @Liaojinghui Just create your own nuget store on your computers file system
> 
> https://learn.microsoft.com/en-us/nuget/hosting-packages/local-feeds

But why not add it to the monorepo directly,,,,much easier

2023-11-16 14:04 UTC, Liaojinghui commented
> So move it all for now and let's see this experience.

@vncoelho I tried to remove the DUP, but still wont work, I think there are logic issues in the convert.

2023-11-16 16:47 UTC, Liaojinghui commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        public BigInteger ValueA { [Safe] get; protected set; }
```suggestion
        public static BigInteger ValueA { [Safe] get; protected set; }
```

2023-11-16 16:49 UTC, Liaojinghui commented on tests/Neo.SmartContract.Framework.UnitTests/Services/BackedStorageTest.cs
> +            Assert.AreEqual(new BigInteger(0), result.Pop().GetInteger());
```suggestion
            Assert.IsTrue(result.Pop().IsNull);
```

2023-11-16 16:54 UTC, Liaojinghui commented
Good to go now @shargon

2023-11-16 16:54 UTC, Liaojinghui approved these changes

2023-11-16 18:21 UTC, shargon commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        public BigInteger ValueA { [Safe] get; protected set; }
We should test it with and without static

2023-11-16 18:23 UTC, shargon commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        public BigInteger ValueA { [Safe] get; protected set; }
And using public getters and setters

2023-11-16 23:30 UTC, Liaojinghui commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        public BigInteger ValueA { [Safe] get; protected set; }
> We should test it with and without static

Can you please clearify the behavior? You want non-static values behave the same as static values when marked as Storage? BTW, i suggest to rename as `Storage` instead of `StorageBacked`

2023-11-17 09:58 UTC, shargon commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        public BigInteger ValueA { [Safe] get; protected set; }
> I would suggest to remove storageback support for non-static.

Why if we allow non-static methods?

2023-11-17 10:19 UTC, shargon reviewed
@superboyiii could you test this new feature?

2023-11-17 11:47 UTC, Liaojinghui commented
@shargon getter is public by default, but do you think we should also add private getter UT tests?

2023-11-17 11:50 UTC, shargon commented
> @shargon getter is public by default, but do you think we should also add private getter UT tests?

Yes, all unit tests as possible

2023-11-17 13:41 UTC, Liaojinghui commented
My bad on the previous commit, working on fixing

2023-11-17 13:47 UTC, Liaojinghui approved these changes

2023-11-17 13:48 UTC, Liaojinghui commented
@superboyiii  please double check.

2023-11-17 15:19 UTC, shargon commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        [StorageBacked]
I want to test with different kind of prefixes

2023-11-17 15:21 UTC, Liaojinghui commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        [StorageBacked]
i think i did not change yours, its something that I added for the getter and setter tests

2023-11-17 15:33 UTC, Liaojinghui commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        public BigInteger ValueA { [Safe] get; protected set; }
> BTW, i suggest to rename as `Storage` or `Singleton` or `Global` instead of `StorageBacked`

@shargon will you consider this? Storageback is a weird name.

2023-11-18 09:42 UTC, shargon commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        public BigInteger ValueA { [Safe] get; protected set; }
`StorageAttribute`

2023-11-18 10:05 UTC, Liaojinghui commented on tests/Neo.SmartContract.Framework.UnitTests/TestClasses/Contract_StorageBacked.cs
> +        public BigInteger ValueA { [Safe] get; protected set; }
I vote the first one.

2023-12-12 13:38 UTC, Liaojinghui approved these changes

2023-12-12 23:16 UTC, shargon commented
Ping @superboyiii

2023-12-14 05:14 UTC, superboyiii commented
> Ping @superboyiii

I will

2023-12-15 08:07 UTC, superboyiii commented
Tested, it works for me. But seems it's not a correct exception message when someone not owner invoke `private set`.
![1702627641228](https://github.com/neo-project/neo-devpack-dotnet/assets/38493437/122b63f8-76d4-449c-a8a7-bc269301efa5)

2023-12-15 10:44 UTC, shargon commented
> Tested, it works for me. But seems it's not a correct exception message when someone not owner invoke `private set`. @shargon @Liaojinghui `Not Owner invocation` ![1702627641228](https://private-user-images.githubusercontent.com/38493437/290763412-122b63f8-76d4-449c-a8a7-bc269301efa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzczNDIsIm5iZiI6MTcwMjYzNzA0MiwicGF0aCI6Ii8zODQ5MzQzNy8yOTA3NjM0MTItMTIyYjYzZjgtNzZkNC00NDljLWE4YTctYmMyNjkzMDFlZmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEwNDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZTdmZjk2ZDEzYzU4NDQ4NzU5YmI0ZjNkMjM3MzgwMjgxMDliODkzZjg0Njg0MGRmMzQzOTQ1ZWZiZTUzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hbj6rPmJ9fBG6dCiaE7vhcTaSZsz2Nrfphagr1kS4_o)
> 
> `Owner invocation` ![1702627954189](https://private-user-images.githubusercontent.com/38493437/290764693-a1dc4f46-1340-4046-9aa6-54e868f81c16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzczNDIsIm5iZiI6MTcwMjYzNzA0MiwicGF0aCI6Ii8zODQ5MzQzNy8yOTA3NjQ2OTMtYTFkYzRmNDYtMTM0MC00MDQ2LTlhYTYtNTRlODY4ZjgxYzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEwNDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZDVlMTllOTAxODhlYjk3ODMxYWVjNDdkYzhkMmVjYmE0MzhlMTY5ODFiOGQzNWM3OWMyOGY5M2E3NjBiMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gUYIj_CgLFwWT3MHVeY0id_4FkLGtolLe0NlwRlz2Uw)

Could you open a issue in neo-modules, seems that the error when a method is not found is not well described

2023-12-15 10:45 UTC, shargon approved these changes

2023-12-15 10:45 UTC, merged

2023-12-18 02:33 UTC, superboyiii commented
> Could you open a issue in neo-modules, seems that the error when a method is not found is not well described

Sorry, it's becasue of the different scope accout from opened account.

2023-12-18 02:46 UTC, superboyiii commented
I tried to invoke a private set with an account differring from owner address, but can get the value without any interaction with owner address from deploying. Is this an expected behaviour? @Liaojinghui  @shargon 
```
//initial operator
        [InitialValue("NTADuu5qt2Rt2tder3dx4RDAWjsKozxdMT", ContractParameterType.Hash160)]
        private static readonly UInt160 Owner = default;
```

```
[StorageBacked]
        public static string Test
        {
            get;
            private set;
        }

        public static void TryTest2()
        {
            Test = "abc";
        }

        [Safe]
        public string getTest() => Test;
```

![1702867505846](https://github.com/neo-project/neo-devpack-dotnet/assets/38493437/50837cf1-db0f-4eb6-8ded-28005b5d599f)

![1702867530273](https://github.com/neo-project/neo-devpack-dotnet/assets/38493437/6e9df4c9-ec83-4488-ac82-bc52ecbf9166)

![1702867664948](https://github.com/neo-project/neo-devpack-dotnet/assets/38493437/ee62ea3a-0d20-4049-8869-63afee05e61d)

2023-12-18 06:00 UTC, Liaojinghui commented
how is that possible to invoke a private set? its not in the abi

2023-12-18 06:02 UTC, superboyiii commented
> how is that possible to invoke a private set? its not in the abi

I mean invoke `tryTest2` method here.

2023-12-18 06:03 UTC, superboyiii commented
> how is that possible to invoke a private set? its not in the abi...oh, you are calling a private set in an interface. Of course it is expected. if user does not add permission to the interface, ofcourse it can be called.

Why don't make the private set method check owner witness?

2023-12-18 06:21 UTC, Liaojinghui commented
Well, i am not sure, but isn't this a default behavior of all private methods in neo contract? you explicitely add checks, instead of by us.

2023-12-18 06:29 UTC, superboyiii commented
> Well, i am not sure, but isn't this a default behavior of all private methods in neo contract? you explicitely add checks, instead of by us.
I've already set that in verfy(), is this not enough?
![1702880982142](https://github.com/neo-project/neo-devpack-dotnet/assets/38493437/b83ff8e8-9d31-4a8d-9f39-e399e7834ad9)

2023-12-18 06:59 UTC, superboyiii commented
OK, I see. This private function is not a private function for owner but just can't be seen in Abi. Owner still need manually set funcB to invoke funcA and manually add checkwitness(owner) if he need execute funcA...