optimizer to remove unused instructions
neo-project/neo-devpack-dotnet pull request #879
Opened 2024-01-30 10:14 UTC by Hecate2

- I used an individual namespace Neo.Optimizer. This is to prevent conflict between Neo.VM.Instruction and Neo.Compiler.Instruction, and to indicate that Neo.Optimizer optimizes contracts written by all languages, not only C#.
- I passed all tests, but I am not really sure whether my optimizations had been applied...

2024-01-31 14:03 UTC, Jim8y commented
Please put your file into a folder.

2024-01-31 14:05 UTC, Hecate2 commented
> Please put your files into a folder.

WILCO

2024-02-01 05:32 UTC, Hecate2 commented
There is still bug:
https://github.com/Hecate2/neo-devpack-dotnet/blob/d4523dae603ff25000b0be527360fb482544ec59/src/Neo.Compiler.CSharp/Optimizer/AssemblyOptimizer.cs#L106-L116
I did not remove `methodsToRemove` from debugInfo

2024-02-05 13:42 UTC, Jim8y approved these changes

2024-02-05 13:42 UTC, Jim8y commented
@superboyiii @shargon @cschuchardt88  please review

2024-02-06 07:01 UTC, cschuchardt88 requested changes
Please make changes before we can merge. Please keep the coding style the same.

2024-02-06 07:01 UTC, cschuchardt88 commented on src/Neo.Compiler.CSharp/Optimizer/Strategies/Reachability.cs
> +                Regex sequencePointRegex = new Regex(@"(\d+)(\[\d+\]\d+\:\d+\-\d+\:\d+)");
Use compiled regex.

2024-02-06 07:01 UTC, cschuchardt88 commented on src/Neo.Compiler.CSharp/Optimizer/Strategies/Reachability.cs
> +                    Regex documentRegex = new Regex(@"\[(\d+)\](\d+)\:(\d+)\-(\d+)\:(\d+)");
Use Compiled regex.

2024-02-06 07:03 UTC, Hecate2 commented
> Please make changes before we can merge.

OK

2024-02-06 07:04 UTC, cschuchardt88 commented
Please keep the coding style the same.

2024-02-06 07:07 UTC, Hecate2 commented on src/Neo.Compiler.CSharp/Optimizer/DumpNef.cs
> +                return Encoding.Default.GetString(unzippedArray);
`Zip` and `Unzip` are utility functions and are not used for now. Will delete them.

2024-02-06 07:08 UTC, cschuchardt88 commented
@Jim8y we dont have the `.editorconfig` on this repo?

2024-02-06 13:55 UTC, Jim8y commented
> @Jim8y we dont have the `.editorconfig` on this repo?

You can add it

2024-02-07 04:01 UTC, cschuchardt88 reviewed
Looks good.

2024-02-07 04:01 UTC, cschuchardt88 commented on src/Neo.Compiler.CSharp/Optimizer/DumpNef.cs
> +            using var archive = new ZipArchive(zippedBuffer);
You may want to do `ZipArchive(zippedBuffer, Encoding.UTF8, false);` to ensure that encoding for the `GetString` method below.

2024-02-08 02:08 UTC, Hecate2 commented on src/Neo.Compiler.CSharp/Optimizer/DumpNef.cs
> +                return Encoding.UTF8.GetString(unzippedArray);
Zip and Unzip methods are used for debug info (.nefdbgnfo) files. The debug info is a zip archive, containing a single .debug.json file inside.

2024-02-08 12:44 UTC, cschuchardt88 approved these changes

2024-02-08 13:11 UTC, Jim8y commented
@shargon

2024-02-09 14:23 UTC, shargon reviewed
> I passed all tests, but I am not really sure whether my optimizations had been applied...

Could you create a unit test for each optimization?

> My own tests did not verify rarely-seen Instructions like ENDFINALLY and ASSERTMSG. They may not be handled correctly.

This is scary, could you add a unit test to ensure that this blocks are well optimized?

2024-02-09 14:23 UTC, shargon commented on tests/Neo.SmartContract.TestEngine/TestEngine.cs
> +        public CompilationContext AddEntryScript(bool optimize = true, bool debug = true, params string[] files)
Maybe false by default...

2024-02-09 14:27 UTC, merged

2024-02-09 14:33 UTC, shargon commented
I will revert it, sorry

2024-02-09 14:47 UTC, shargon commented
@Hecate2 could you create a new pr for the unit tests?

2024-02-09 14:49 UTC, Hecate2 commented
> @Hecate2 could you create a new pr for the unit tests?

OK. Yet I am still wondering how to test huge contracts in C# running quickly in github actions.

2024-02-09 15:35 UTC, shargon commented
I have in mind a way, not only for c#, for all nef contracts to be tested easily

2024-02-12 22:47 UTC, shargon commented
@Hecate2 I can confirm that it didn't work with `TRY` blocks could you take a look or avoid it?

2024-02-12 23:51 UTC, cschuchardt88 commented
> > @Hecate2 could you create a new pr for the unit tests?
> 
> OK. Yet I am still wondering how to test huge contracts in C# running quickly in github actions.

`neo-express` has a tool library for `XUnit` https://github.com/neo-project/neo-express/tree/master/src/test-harness. We use it in the `neo-express` github actions I believe. However it uses `neo-express` node to execute contract.

Here's how to use. https://github.com/cschuchardt88/neo-examples-csharp/tree/master/tests/Contract.Tests

maybe you can code up something.

2024-02-13 12:40 UTC, Hecate2 commented
> @Hecate2 I can confirm that it didn't work with `TRY` blocks could you take a look or avoid it?

I found the problem. Working on the PR