[Framework] this pr focus on adding smallest unit of GAS
neo-project/neo-devpack-dotnet pull request #885
Opened 2024-02-07 13:17 UTC by Jim8y

This pr focus on adding smallest unit of GAS,

it add satoshi, ksatoshi, msatoshi.

2024-02-07 13:19 UTC, Jim8y commented on src/Neo.SmartContract.Framework/Neo.SmartContract.Framework.csproj
> +    <Compile Update="ContractTypes\UInt256.cs">
```suggestion
```

2024-02-07 13:19 UTC, Jim8y commented on src/Neo.SmartContract.Framework/Neo.SmartContract.Framework.csproj
> +    </Compile>
```suggestion
```

2024-02-07 13:20 UTC, Jim8y commented on tests/Neo.Compiler.CSharp.TestContracts/Contract1.cs
> +            return "NEO3" + b + c + d;
```suggestion
           return "NEO3";
```

2024-02-07 13:21 UTC, Jim8y commented on tests/Neo.Compiler.CSharp.TestContracts/Contract1.cs
> +           return "NEO3";
```suggestion
            return "NEO3";
```

2024-02-07 13:21 UTC, Jim8y commented on tests/Neo.Compiler.CSharp.TestContracts/Contract1.cs
> +
```suggestion
```

2024-02-07 13:23 UTC, Jim8y commented on tests/Neo.Compiler.CSharp.TestContracts/Contract1.cs
> +
```suggestion
```

2024-02-10 10:24 UTC, cschuchardt88 requested changes
Remove all the renames and create another `PR` or edit  `1st comment` and `title` to describe what this PR is suppose to do. Because as it sits; this `PR` isn't doing what it says it needs to do.

2024-02-11 04:51 UTC, closed without merging