Creating Artifacts from nef
neo-project/neo-devpack-dotnet pull request #890
Opened 2024-02-09 19:32 UTC by shargon

Part of https://github.com/neo-project/neo-devpack-dotnet/issues/889

2024-02-10 10:11 UTC, cschuchardt88 requested changes

2024-02-10 10:11 UTC, cschuchardt88 commented on tests/Neo.SmartContract.TestEngine.UnitTests/ArtifactsTests.cs
> +                @"{""name"":""Contract1"",""groups"":[],""features"":{},""supportedstandards"":[""NEP-17""],""abi"":{""methods"":[{""name"":""symbol"",""parameters"":[],""returntype"":""String"",""of
Please do not write strings like this. 

Use `\"`

How are we to know where `"` starts and stop?

2024-02-10 10:11 UTC, cschuchardt88 commented on tests/Neo.SmartContract.TestEngine.UnitTests/GlobalUsings.cs
> +global using NUnit.Framework;
**DO NOT** use `NUnit` its the worst when it comes to test frameworks. Use `XUnit`

2024-02-10 10:37 UTC, cschuchardt88 commented on neo-devpack-dotnet.sln
> +EndProject
This is corrupt; the solution file. Don't rename projects. Delete and add a new one. It does this on source control repos. If it's already committed with that name. and when you rename it, it just adds the new project. If you delete and add new project. It will change all the GUIDs. which is what you want.

2024-02-10 10:39 UTC, cschuchardt88 commented on neo-devpack-dotnet.sln
> +EndProject
This is almost why i said to not use `NUnit` it sucks.

2024-02-10 10:50 UTC, shargon commented on tests/Neo.SmartContract.TestEngine.UnitTests/ArtifactsTests.cs
> +                @"{""name"":""Contract1"",""groups"":[],""features"":{},""supportedstandards"":[""NEP-17""],""abi"":{""methods"":[{""name"":""symbol"",""parameters"":[],""returntype"":""String"",""of
it's a unit test, visual studio by default use this style when you copy and pase inside

2024-02-10 19:05 UTC, shargon commented
Waiting for https://github.com/neo-project/neo/pull/3133 to clean the UTs

2024-02-11 13:52 UTC, shargon commented on tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
> +            Assert.AreEqual(123, engine.Execute(script.ToArray()).GetInteger());
Now it's able to mock any contract call :) it will be easier to do Unit tests :D

2024-02-11 13:59 UTC, shargon commented
I will write a `Readme.md` explaining the unit test engine, I think is almost done, we can change the default protocolSettings by wallets stored in TestEngine, but it's working now :)

2024-02-11 21:18 UTC, shargon commented
Ready to review @neo-project/core

2024-02-11 21:19 UTC, shargon commented
Ready to review @neo-project/core

2024-02-11 23:43 UTC, shargon commented on src/Neo.SmartContract.Testing/NativeArtifacts.cs
> +                        throw new Exception($"Error executing {native.Name}.OnPersist");
```suggestion
                        throw new Exception($"Error executing {native.Name}.PostPersist");
```

2024-02-11 23:43 UTC, shargon commented on src/Neo.SmartContract.Testing/README.md
> +// Engine an contract creation
```suggestion
// Create engine and initialize native contracts
```

2024-02-12 10:48 UTC, vncoelho reviewed
Very good, @shargon 

I started checking the code. I will soon finish the review.

2024-02-12 12:23 UTC, shargon commented
> @belane is back...
> 
> @shargon, I will clone the repo and try to test with an example as well, creating some tests. Maybe I will finish just Thursday.

Perfect, @belane and me tried the `Deploy` and it works perfect :), I want to do the unit test of nep17 template after merge this PR.

2024-02-12 14:18 UTC, vncoelho commented on tests/Neo.SmartContract.Testing.UnitTests/SmartContractStorageTests.cs
> +            // Engine an contract creation
a contract

2024-02-12 14:20 UTC, vncoelho commented on tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
> +        //[TestMethod]
why test is commented?

```cs
        foreach (var n in Native.NativeContract.Contracts)
        {
            var manifest = n.Manifest;
            var source = manifest.Abi.GetArtifactsSource(manifest.Name);

            File.WriteAllText($"{manifest.Name}.cs", source);
        }
```


This use case is very good, although it is quite strange to use the submodule to extract those contracts here and test them in this repo instead of testing there.

However, it is great to be allowed to test it here!

2024-02-12 14:21 UTC, vncoelho commented on tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
> +            Assert.AreEqual(123, neo.BalanceOf(engine.ValidatorsAddress));
very good!

2024-02-12 14:21 UTC, vncoelho commented on tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
> +                Assert.AreEqual(123, engine.Execute(script.ToArray()).GetInteger());
congratz

2024-02-12 14:38 UTC, shargon commented on tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
> +        //[TestMethod]
I used manually to create the native artifacts that is used in `Engine.Native`

2024-02-12 14:45 UTC, shargon commented on tests/Neo.SmartContract.Testing.UnitTests/SmartContractStorageTests.cs
> +            // Engine an contract creation
Fixed

2024-02-12 14:54 UTC, vncoelho commented on tests/Neo.SmartContract.Testing.UnitTests/TestEngineTests.cs
> +        //[TestMethod]
Sure, this is good.
I just mean that it is not perfect to test it here instead of testing in the neo core itself.
From this perspective it would be good to test it directly there. But it will be a reverse logic for now.

2024-02-12 14:56 UTC, vncoelho commented on src/Neo.SmartContract.Testing/README.md
> +- Receive events during the deploy, because the object is returned after performing the deploy, it is not possible to intercept notifications for the deploy unless the contract is previously created
Very good to known.
Later, maybe we could create a function to facilitate with an example of a calculation of a hash and the track of this event.

2024-02-12 15:10 UTC, vncoelho commented
![image](https://github.com/neo-project/neo-devpack-dotnet/assets/17395762/051e7a3b-b116-4889-9bcc-f6ad6bf17668)

@shargon, updated devcontainer here to facilitate the verification of tests

2024-02-12 15:11 UTC, vncoelho commented on .vscode/settings.json
> +    "dotnet.defaultSolution": "neo-devpack-dotnet.sln"
since there are multiple solutions with submodule we need this to facilitate.

I can create another PR. But I mistaked push to the branch ahueahueahueuha
I think it is ok.

2024-02-12 15:33 UTC, vncoelho commented
@shargon,

Is the solution file correct?

Should not it be more clean, because everything from the submodule is being added there.

2024-02-12 16:14 UTC, shargon commented on neo-devpack-dotnet.sln
> +VisualStudioVersion = 17.7.34003.232
> Should not this file be more clean instead of adding all projects from submodule?

It's an automatic change

2024-02-12 16:20 UTC, vncoelho commented on neo-devpack-dotnet.sln
> +VisualStudioVersion = 17.7.34003.232
What command generates that?

2024-02-12 16:21 UTC, cschuchardt88 commented
`neo-express` has something you want to look at for testing contracts. It work very well. Currently still works and what i been using.

https://github.com/cschuchardt88/neo-express/tree/master/src/test-harness

2024-02-12 16:23 UTC, cschuchardt88 commented on neo-devpack-dotnet.sln
> +VisualStudioVersion = 17.7.34003.232
> What command generates that?

`dotnet add project`

or visual studio

2024-02-12 17:06 UTC, shargon commented on neo-devpack-dotnet.sln
> +VisualStudioVersion = 17.7.34003.232
Visual studio

2024-02-12 17:44 UTC, shargon commented
> `neo-express` has something you want to look at for testing contracts. It work very well. Currently still works and what i been using. It is written for the testing framework `XUint`. However still think the testing environment should plugin into a test framework. Either `mstests` or `XUint`, 100% not `NUnit`
> 
> https://github.com/neo-project/neo-express/tree/master/src/test-harness

I can take ideas about stacked invocations, thanks!

2024-02-12 18:22 UTC, cschuchardt88 commented
> stacked invocations

https://github.com/neo-project/neo-express/tree/master/src/assertions    ?

Code Coverage Data -  https://github.com/neo-project/neo-express/tree/master/src/collector?

If any of that helps.

2024-02-12 18:34 UTC, shargon commented
> Collecting Code Coverage Data - https://github.com/neo-project/neo-express/tree/master/src/collector? Could use this for contract code coverage
> 
> If any of that helps.

I think it is feasible to calculate the coverage, and the `NeoDebugInfo` class can make it much easier for me, I will implement it in a next version :)

2024-02-12 19:13 UTC, cschuchardt88 reviewed
Really think you should look into a mocking framework like `moq`. However it looks good, could be great but a great start. After questions answered or no more changes I will approve.

2024-02-12 19:13 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Native/ContractManagement.cs
> +public abstract class ContractManagement : Neo.SmartContract.Testing.SmartContract
Would be better to use an `Interface`.

2024-02-12 19:13 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Native/ContractManagement.cs
> +    [DisplayName("Deploy")]
Attributes get ignored on derived class when inheriting. Use `Interface`

2024-02-12 19:13 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/NativeArtifacts.cs
> +        private StdLib? _stdLib;
Can't these be created on `constructor`. We do have `_engine` as `readonly` we should be loading and checking once. Unless the engine can change these variables in the middle of the execution.

2024-02-12 22:15 UTC, shargon commented on src/Neo.SmartContract.Testing/Extensions/MockExtensions.cs
I use moq, this is only because moq didn't allow to moq types by Type, so I use reflection here to use moq

2024-02-12 22:16 UTC, shargon commented on src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
> +                return sourceCode.ToString().Replace("\r\n", "\n").Trim();
I have never seen this property, you are as nice as always, however thank you

2024-02-12 22:28 UTC, shargon commented on src/Neo.SmartContract.Testing/Native/ContractManagement.cs
> +public abstract class ContractManagement : Neo.SmartContract.Testing.SmartContract
I can't have methods, and store information in a interface

2024-02-12 22:44 UTC, shargon commented on src/Neo.SmartContract.Testing/Native/ContractManagement.cs
> +    [DisplayName("Deploy")]
It's working

2024-02-12 23:23 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Extensions/MockExtensions.cs
oh. I need to pay attention more than.

2024-02-12 23:26 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Native/ContractManagement.cs
> +    [DisplayName("Deploy")]
well that's news to be and i been around the block. Must be dotnet standard thing than.

2024-02-12 23:45 UTC, cschuchardt88 approved these changes

2024-02-13 07:59 UTC, shargon commented
@cschuchardt88 @Jim8y merge? I will improve it in a new PR (Gas cost per instruction and method)

2024-02-13 09:15 UTC, cschuchardt88 approved these changes

2024-02-13 12:01 UTC, merged

2024-02-13 12:01 UTC, shargon commented
I need this merged to continue working on, Improvements can be incorporated in future pull requests.

2024-02-16 11:24 UTC, vncoelho reviewed
Finished reviewing today.