Draft Nep17 UT
neo-project/neo-devpack-dotnet pull request #893
Opened 2024-02-12 14:15 UTC by shargon

Require https://github.com/neo-project/neo-devpack-dotnet/pull/890

2024-02-12 14:24 UTC, vncoelho commented on src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
> +    [DisplayName(nameof(Nep17Contract))]
good

2024-02-12 14:24 UTC, vncoelho reviewed
Very good, @shargon 
I was exactly here setting up my devcontainer to try something with NEP17

2024-02-12 14:25 UTC, vncoelho commented on tests/Neo.SmartContract.Template.UnitTests/nep17/Nep17Tests.cs
> +            var nef = File.ReadAllBytes("nep17/UtArtifacts/Nep17Contract.nef");
why not compile it here instead?
Are you sure to upload the .nef compiled? We would need to change this every release or every commit in order to stay concise.

2024-02-12 15:03 UTC, vncoelho commented on tests/Neo.SmartContract.Template.UnitTests/nep17/Nep17Tests.cs
> +            var nef = File.ReadAllBytes("nep17/UtArtifacts/Nep17Contract.nef");
What do you mean by that? I did not understand.
In this PR or later you mean?

2024-02-12 16:07 UTC, shargon commented on tests/Neo.SmartContract.Template.UnitTests/nep17/Nep17Tests.cs
> +            var nef = File.ReadAllBytes("nep17/UtArtifacts/Nep17Contract.nef");
In this PR

2024-02-12 16:10 UTC, shargon commented on tests/Neo.SmartContract.Template.UnitTests/nep17/Nep17Tests.cs
> +            var nef = File.ReadAllBytes("nep17/UtArtifacts/Nep17Contract.nef");
The problem with compile, is that the template has an invalid framework version

2024-02-12 16:11 UTC, vncoelho commented on tests/Neo.SmartContract.Template.UnitTests/nep17/Nep17Tests.cs
> +            var nef = File.ReadAllBytes("nep17/UtArtifacts/Nep17Contract.nef");
What do you mean?

2024-02-12 16:11 UTC, vncoelho commented on tests/Neo.SmartContract.Template.UnitTests/nep17/Nep17Tests.cs
> +            var nef = File.ReadAllBytes("nep17/UtArtifacts/Nep17Contract.nef");
The framework source is also here

2024-02-12 17:00 UTC, shargon reviewed
@Jim8y any idea about this error?

> Severity	Code	Description	Project	File	Line	Suppression State
Error	NC1002	Unknown method: Neo.SmartContract.Framework.TokenContract.TotalSupply.get	Neo.SmartContract.Template.UnitTests	C:\Neo\neo-devpack-dotnet\tests\Neo.SmartContract.Template.UnitTests\EXEC	1

2024-02-12 17:06 UTC, cschuchardt88 commented
> @Jim8y any idea about this error?
> 
> > Severity	Code	Description	Project	File	Line	Suppression State
> > Error	NC1002	Unknown method: Neo.SmartContract.Framework.TokenContract.TotalSupply.get	Neo.SmartContract.Template.UnitTests	C:\Neo\neo-devpack-dotnet\tests\Neo.SmartContract.Template.UnitTests\EXEC	1

```csharp
[Stored(Prefix_TotalSupply)]
public static BigInteger TotalSupply { [Safe] get; protected set; }
```

2024-02-12 17:16 UTC, shargon commented
> > @Jim8y any idea about this error?
> > > Severity	Code	Description	Project	File	Line	Suppression State
> > > Error	NC1002	Unknown method: Neo.SmartContract.Framework.TokenContract.TotalSupply.get	Neo.SmartContract.Template.UnitTests	C:\Neo\neo-devpack-dotnet\tests\Neo.SmartContract.Template.UnitTests\EXEC	1
> 
> ```cs
> [Stored(Prefix_TotalSupply)]
> public static BigInteger TotalSupply { [Safe] get; protected set; }
> ```
> 
> The code changed. Maybe move `[Stored(Prefix_TotalSupply)]` to `set`?

In the `Contract_StorageBacked` is exactly like this :S

2024-02-13 12:22 UTC, shargon commented
It should work with https://github.com/neo-project/neo-devpack-dotnet/pull/895

2024-02-13 12:33 UTC, shargon commented on src/Neo.Compiler.CSharp/Options.cs
> +        public bool GenerateArtifactLibrary { get; set; }
@Jim8y this don't allow enums?

2024-02-13 12:33 UTC, shargon commented on tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs
> +            var nep17 = Engine.Deploy<Nep17Contract>(nef, manifest, null);
```suggestion
            var nep17 = Engine.Deploy<Nep17Contract>(nef, manifest, rand);
```

2024-02-13 13:28 UTC, shargon commented
@Jim8y could you take a look, I receive CS1545 error with events, It seems like the artifacts compilation use a different type of UInt160 and events don't work, with source it works

2024-02-13 13:30 UTC, shargon commented on tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj
> +		<Exec Command="dotnet add    &quot;$(SolutionDir)src/Neo.SmartContract.Template/$(OutputPath)/Nep17Contract.csproj&quot; reference &quot;$(SolutionDir)src/Neo.SmartContract.Framework/Neo.SmartContr
This is more complex because it's a template, in regular projects this can be avoided.

2024-02-13 13:32 UTC, shargon commented on tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj
> +	    <HintPath>templates\neocontractnep17\Artifacts\Nep17Contract.artifacts.dll</HintPath>
I think it's cleaner with the dll, but currently it didn't work if we change to source, it works now.

2024-02-13 15:20 UTC, cschuchardt88 requested changes

2024-02-13 15:20 UTC, cschuchardt88 commented on src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
You can't change the template path. It wont work. Its what `dotnet` requires for you to install them.

2024-02-13 15:26 UTC, cschuchardt88 commented on src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
i'll put in pr to fix.

2024-02-13 15:46 UTC, cschuchardt88 commented on src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
That's because your using old un-support format then.

2024-02-13 20:11 UTC, shargon commented on src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
I changed only the project's name, i don't know why this should not work in any format

2024-02-14 09:11 UTC, shargon commented
I summarize the problem:

- Artifacts generated when compiling the template can be in .cs or .dll.
- I pretend not to have the files in the artifacts folder, just copy them during compilation.
- If I copy the .cs, the file must be included in the compilation, it can be done with msbuild, but it is more complex.
- If I copy the dll the compilation works directly in preBuild, but I don't know why the events doesn't work.

First of all, how do you think it should be, with the compiled dll or with the source? @cschuchardt88 @Jim8y

2024-02-14 16:42 UTC, cschuchardt88 commented
This how `neo-express` tests `nef` files https://github.com/neo-project/neo-express/tree/master/src/runner in accordance with using build tasks https://github.com/neo-project/neo-express/tree/master/src/build-tasks for `neo-express`'s engine.

2024-02-14 17:51 UTC, Jim8y commented on tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj
> +		<Nullable>enable</Nullable>
Alignment

2024-02-14 22:57 UTC, shargon commented
> This how `neo-express` tests `nef` files https://github.com/neo-project/neo-express/tree/master/src/runner in accordance with using build tasks https://github.com/neo-project/neo-express/tree/master/src/build-tasks for `neo-express`'s engine.
> 
> Also we want code coverage data https://github.com/neo-project/neo-express/tree/master/src/collector
> 
> Should be able to use both compiled and source.

It's a different way, they need a invoke file, I want to use dotnet unit tests, it doesn't work for me.

2024-02-15 01:18 UTC, cschuchardt88 commented
> > This how `neo-express` tests `nef` files https://github.com/neo-project/neo-express/tree/master/src/runner in accordance with using build tasks https://github.com/neo-project/neo-express/tree/master/src/build-tasks for `neo-express`'s engine.
> > Also we want code coverage data https://github.com/neo-project/neo-express/tree/master/src/collector
> > Should be able to use both compiled and source.
> 
> It's a different way, they need a invoke file, I want to use dotnet unit tests (more user friendly), it doesn't work for me.

That's fine.

2024-02-15 10:01 UTC, shargon commented
Nep 17 template coverage
```
0x9e4064b25f076be69907002e50cdec719f0759a0 [92.93 %%]
┌-─────────────-┬-────────-┐
│ totalSupply,0 │ 100.00 % │
│ balanceOf,1   │  99.15 % │
│ transfer,4    │  86.56 % │
│ getOwner,0    │  95.24 % │
│ setOwner,1    │  90.70 % │
│ burn,2        │  91.67 % │
│ mint,2        │  91.67 % │
│ verify,0      │ 100.00 % │
│ myMethod,0    │ 100.00 % │
│ _deploy,2     │  94.12 % │
│ update,3      │  90.91 % │
│ _initialize,0 │ 100.00 % │
│ symbol,0      │ 100.00 % │
│ decimals,0    │ 100.00 % │
└-─────────────-┴-────────-┘
```

2024-02-15 10:55 UTC, shargon commented
@Jim8y @cschuchardt88 the code is ready, and now it's working in workflow because the artifacts is already in the folder, and when it compile is the same, this is something that we should fix it in a different pr, we should be able to have empty the artifacts folder, and use the compiled one or the source one using only msbuild.

2024-02-15 11:37 UTC, shargon commented
@Jim8y any idea about why the coverage dump is not printed in workflow logs?

2024-02-15 12:23 UTC, shargon reviewed
@cschuchardt88 @Jim8y ready to test, work with workflow and work in visual studio, it generate the artifacts from the template, and change the template smart contract framework version to use the current one, so the template pack is also tested.

2024-02-15 14:19 UTC, Jim8y commented on src/Neo.Compiler.CSharp/Program.cs
> +                new Option<Options.GenerateArtifactsKind>("--generate-artifacts", "Instruct the compiler how to generate artifacts."),
How do we specify this from console?

2024-02-15 14:23 UTC, shargon commented on src/Neo.Compiler.CSharp/Program.cs
> +                new Option<Options.GenerateArtifactsKind>("--generate-artifacts", "Instruct the compiler how to generate artifacts."),
`--generate-artifacts source`

2024-02-15 14:23 UTC, Jim8y commented
Unit test issue, run 
```shell
dotnet test
```

Error 

```
A total of 1 test files matched the specified pattern.
  Failed TestMintAndBurn [9 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<10>. Actual:<14>. 
  Stack Trace:
     at Neo.SmartContract.Template.UnitTests.templates.neocontractnep17.Nep17ContractTests.TestMintAndBurn() in /Users/jinghuiliao/git/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs:line 192
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

2024-02-15 14:24 UTC, shargon commented
> Unit test issue, run
> 
> ```shell
> dotnet test
> ```
> 
> Error
> 
> ```
> A total of 1 test files matched the specified pattern.
>   Failed TestMintAndBurn [9 ms]
>   Error Message:
>    Assert.AreEqual failed. Expected:<10>. Actual:<14>. 
>   Stack Trace:
>      at Neo.SmartContract.Template.UnitTests.templates.neocontractnep17.Nep17ContractTests.TestMintAndBurn() in /Users/jinghuiliao/git/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs:line 192
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
> ```

I think is something related in the order of execution

2024-02-15 14:25 UTC, Jim8y commented
every single test should run in seperate env right?

2024-02-15 14:30 UTC, shargon commented
> every single test should run in seperate env right? Maybe not testengine, but MockTestENgine

I tried to use the same engine, that could be a problem if they not ends clean

2024-02-15 14:42 UTC, shargon commented on tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs
> +            Console.WriteLine(Coverage.Dump());
@Jim8y I don't know why this is not printed in the workflow log, it's printed in my VisualStudio

2024-02-15 14:43 UTC, shargon commented on tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs
> +            Console.WriteLine(Coverage.Dump());
maybe `dotnet test` don't call `AssemblyCleanup`?

2024-02-15 15:02 UTC, shargon commented on .github/workflows/main.yml
> +        -p:CollectCoverage=true \
```suggestion
        -l "console;verbosity=minimal" \
        p:CollectCoverage=true \
```

2024-02-15 15:06 UTC, shargon commented
ready @Jim8y

2024-02-15 15:21 UTC, Jim8y commented
And I can not get Nep17Contract 

```C#
private readonly Nep17Contract Nep17;
```

2024-02-15 15:21 UTC, Jim8y commented
<img width="1026" alt="Screenshot 2024-02-15 at 23 21 33" src="https://github.com/neo-project/neo-devpack-dotnet/assets/10189511/e13ec44e-8a70-4d01-9c3a-a65ceef69b8d">

2024-02-15 15:22 UTC, shargon commented
> And I can not get Nep17Contract
> 
> ```cs
> private readonly Nep17Contract Nep17;
> ```

If fail the postbuild events it doesnt create you the artifacts, take a look to this commands please

2024-02-15 15:27 UTC, Jim8y commented
Bro, not yet going into detail part, should not fault the solution build.

2024-02-15 15:29 UTC, shargon commented
> Bro, not yet going into detail part, should not fault the solution build. Is that possible to do an error handling in there?

It doesn't fail to me, in my computer it works, what versión of dotnet do yo have?

2024-02-15 15:32 UTC, Jim8y commented
> It doesn't fail to me, in my computer it works, what version of dotnet do yo have?

7.0.404

2024-02-15 15:33 UTC, Jim8y commented
quick question, wht these not safe:

```C#
    public abstract BigInteger Decimals { [DisplayName("decimals")] get; }
    public abstract string Symbol { [DisplayName("symbol")] get; }
    public abstract BigInteger TotalSupply { [DisplayName("totalSupply")] get; }
```

2024-02-15 15:35 UTC, Jim8y commented on tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Nep17ContractTests.cs
> +        private readonly Nep17Contract Nep17;
```suggestion
        // You need to build the solution to resolve Nep17Contract class.
        private readonly Nep17Contract Nep17;
```

2024-02-15 15:40 UTC, Jim8y commented
A small suggestion that you may or may not adopt in another pr:

1. hide  to the test engine:
        private static readonly byte[] NefFile;
        private static readonly string Manifest;
        private static CoveredContract Coverage;

2. 5-10 built in Signers.

3. Not using Nep17Contract but a built in general class type where user could assign it as Nep17Contract. Such that we can easily nenerate a as complete as possible unit test project for a contract project.

2024-02-15 15:40 UTC, shargon commented
> quick question, wht these not safe:
> 
> ```cs
>     public abstract BigInteger Decimals { [DisplayName("decimals")] get; }
>     public abstract string Symbol { [DisplayName("symbol")] get; }
>     public abstract BigInteger TotalSupply { [DisplayName("totalSupply")] get; }
> ```

They should be

2024-02-15 15:49 UTC, Jim8y commented
If you still got time, please clean using.

2024-02-15 15:51 UTC, Jim8y commented
@cschuchardt88 this basically redefines all the interface in the Neo.Framework, a duplication for me, and would be kind of hard to maintain in the future, any idea how to make it easier? Not necessary to update is this pr. Can be a future polish.

2024-02-15 16:01 UTC, shargon commented
> Some small suggestions that you may or may not adopt in another pr:
> 
> 1. hide  to the test engine:
>    private static readonly byte[] NefFile;
>    private static readonly string Manifest;
>    private static CoveredContract Coverage;
> 2. 5-10 built in Signers.
> 3. Not using Nep17Contract but a built in general class type where user could assign it as Nep17Contract. Such that we can easily nenerate a as complete as possible unit test project for a contract project.
> 
> And of course unit tests for our template (when we generate project from templete, we also generate a unit test project)

Thanks for your review, amazing idea!

2024-02-15 16:07 UTC, shargon commented
> @cschuchardt88 this basically redefines all the interface in the Neo.Framework, a duplication for me, and would be kind of hard to maintain in the future, any idea how to make it easier? Not necessary to update is this pr. Can be a future polish.

Standard doesn't change so much, it will be easy to maintain

2024-02-15 17:28 UTC, cschuchardt88 requested changes

2024-02-15 17:52 UTC, shargon commented on src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
> +            lock (CoverageData)
I need this thread safe because the UT can be done in parallel.

2024-02-15 17:58 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
> +            lock (CoverageData)
Or use `ConcurrentDictionary` if its a `key`, `value` pair. If its `list` than use a `ConcurrentBag`. Queues use `ConcurrentQueue`

2024-02-15 18:00 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
> +                .OrderBy(o => o.Offset)
This `null` check is false positive, because you are checking it in `where`

2024-02-15 18:05 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
> +            lock (CoverageData)
> I need this thread safe because the UT can be done in parallel.

@shargon what collection is it? Can you use one of the options above?

2024-02-15 19:36 UTC, shargon commented on src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
> +            lock (CoverageData)
If I use ofe of them I can "hit" the entry when is found, but I will need Interlocks and when I try to add a Hit in specific offset, It won't work as expected, if tryAdd fail, I need to retry, It's better to lock the collection, it's done only at the end of the unit tests, nothing to worry about.

2024-02-15 19:37 UTC, shargon commented
@cschuchardt88 @Jim8y your review was applied, now we have `Nep17Tests` and `OwnableTests` ready to be reused in other projects

2024-02-15 19:56 UTC, shargon commented
Next step Nep11 template :) go?

2024-02-16 00:45 UTC, Jim8y submitted a review, later dismissed

2024-02-16 00:46 UTC, Jim8y commented
Try to wait for @cschuchardt88 to check it before merging

2024-02-16 01:49 UTC, cschuchardt88 requested changes
Coming together nicely. Few questions and changes

2024-02-16 01:49 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
> +            lock (CoverageData)
Can we do this then

```csharp
// add global variable.
private readonly object _coverageDataLock = new();
```

Replace 'CoverageData' with the line below  and everywhere else it may need locking.
```csharp
lock (_coverageDataLock )
```

The reason is so we don't lock the `CoverageData` `object` for any longer than needed.



Also change like this?

```csharp
foreach (var c in coverage)
{
    if (c.Hits == 0) continue;

    lock (CoverageData)
    {
        if (CoverageData.TryGetValue(c.Offset, out var kvpValue))
        {
            kvpValue.Hit(c);
        }
        else
        {
            CoverageData.Add(c.Offset, c.Clone());
        }
    }
}
```

2024-02-16 01:49 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Coverage/CoveredContract.cs
> +            if (coverage is null) return;
```suggestion
            if (coverage is null || coverage.Any() == false) return;
```

2024-02-16 01:49 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
> +            if (manifest.SupportedStandards.Contains("NEP-17")) inheritance.Add(typeof(INep17Standard).FullName);
Can we make hardcoded `strings` like `NEP-17` `const` or `static readonly`

2024-02-16 01:49 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
> +                        .Any(u => u.Name == "SetOwner" && u.Parameters.Length == 2 &&
Can we make hardcoded strings be `const` or `static readonly` or use the contracts `manifest` that we are testing?

2024-02-16 01:49 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
> +                        var hasNep17 = manifest.SupportedStandards.Contains("NEP-17");
`const` or `static readonly`? Even a extension method `.HasNep17()` would be nice.

2024-02-16 01:49 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
> +                _ => "object?",
What about `StorageIterator` and other `iterators`?

2024-02-16 01:49 UTC, cschuchardt88 commented on src/Neo.SmartContract.Testing/TestingStandards/TestBase.cs
> +public class TestBase<T> where T : SmartContract
Can we have `contract` `hash`  on this `class`?

2024-02-16 01:49 UTC, cschuchardt88 commented on tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/CoverageContractTests.cs
Is there to add `snapshot` or `checkpoint` for each `Test` `method`?

2024-02-16 03:49 UTC, Jim8y commented on src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
> +                _ => "object?",
They are not  `ContractParameterType`

2024-02-16 08:12 UTC, shargon commented on src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
> +                _ => "object?",
Exactly, If we change the artifacts manually it will work, like ContractManagement.Deploy, I want to change also the rest of them

2024-02-16 08:13 UTC, shargon commented on tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/CoverageContractTests.cs
Yes, we can rollback the storage at the end

2024-02-16 09:14 UTC, shargon commented
> INep17Standard is ussful, would be great if we put it in the framework. Also add a few of other Interfaces for other types of contracts.

Then Testing require this dependency, and can collide types like `UInt160`

2024-02-16 10:04 UTC, Jim8y commented
@shargon any plan to update this https://github.com/neo-project/neo-devpack-dotnet/pull/893#discussion_r1491851690? Or should I just approve.

2024-02-16 11:10 UTC, shargon commented
@Jim8y could you update the submodule in a different pr please?

2024-02-16 11:15 UTC, cschuchardt88 commented on tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/CoverageContractTests.cs
I mean save `checkpoint` for each `test` method that gets invoked. So `test` can cache it if needed to re-run the `test` method again; just for that method.

2024-02-16 11:16 UTC, shargon commented on src/Neo.SmartContract.Testing/Extensions/ArtifactExtensions.cs
> +                _ => "object?",
Done in native contracts only

2024-02-16 11:25 UTC, vncoelho commented on .github/workflows/main.yml
> +        dotnet new neocontractnep17 -n Nep17Contract -o ./src/Neo.SmartContract.Template/bin/Debug/ --force
Is --force needed?

2024-02-16 11:27 UTC, vncoelho commented on src/Neo.Compiler.CSharp/Program.cs
> +                new Option<Options.GenerateArtifactsKind>("--generate-artifacts", "Instruct the compiler how to generate artifacts."),
It is better like this with generate-artifacts instead of no

2024-02-16 11:28 UTC, vncoelho commented on .github/workflows/main.yml
> +        -p:Exclude=\"[Neo.Compiler.CSharp.UnitTests]*\" \
Why just these are excluded?

2024-02-16 11:29 UTC, shargon commented on .github/workflows/main.yml
> +        dotnet new neocontractnep17 -n Nep17Contract -o ./src/Neo.SmartContract.Template/bin/Debug/ --force
Not in workflow, but it works

2024-02-16 11:30 UTC, vncoelho commented on .github/workflows/main.yml
> +        -p:Exclude=\"[Neo.Compiler.CSharp.UnitTests]*\" \
not tests/Neo.SmartContract.Template.UnitTests ?

2024-02-16 11:32 UTC, vncoelho commented on src/Neo.Compiler.CSharp/Program.cs
> +                            // Try to compile the artifacts into a dll
What is this trying to compile artifacts to a dll?

2024-02-16 11:33 UTC, shargon commented on .github/workflows/main.yml
> +        -p:Exclude=\"[Neo.Compiler.CSharp.UnitTests]*\" \
this project execute only nef, it doesn't touch the coverage, will be migrated after this

2024-02-16 11:34 UTC, shargon commented on .github/workflows/main.yml
> +        -p:Exclude=\"[Neo.Compiler.CSharp.UnitTests]*\" \
> not tests/Neo.SmartContract.Template.UnitTests ?

What you mean, this pr create these tests

2024-02-16 11:35 UTC, shargon commented on src/Neo.Compiler.CSharp/Program.cs
> +                            // Try to compile the artifacts into a dll
Because it's not required to have the code, with the dll you can write your unit test also

2024-02-16 11:35 UTC, shargon commented on src/Neo.Compiler.CSharp/Program.cs
> +                            // Try to compile the artifacts into a dll
This can be improved or changed in a different pr

2024-02-16 12:10 UTC, vncoelho reviewed
```cs
/workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Artifacts/Nep17Contract.artifacts.cs(16,89): warning CS0067: The event 'Nep17Contract.OnTransfer' is never used [/workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj]
/workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Artifacts/Nep17Contract.artifacts.cs(13,83): warning CS0067: The event 'Nep17Contract.OnSetOwner' is never used [/workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj]
  Neo.SmartContract.Template.UnitTests -> /workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/bin/Debug/net7.0/Neo.SmartContract.Template.UnitTests.dll

Build succeeded.

/workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Artifacts/Nep17Contract.artifacts.cs(16,89): warning CS0067: The event 'Nep17Contract.OnTransfer' is never used [/workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj]
/workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/templates/neocontractnep17/Artifacts/Nep17Contract.artifacts.cs(13,83): warning CS0067: The event 'Nep17Contract.OnSetOwner' is never used [/workspaces/neo-devpack-dotnet/tests/Neo.SmartContract.Template.UnitTests/Neo.SmartContract.Template.UnitTests.csproj]
    2 Warning(s)
    0 Error(s)
```

2024-02-16 13:29 UTC, vncoelho commented
┌-─────────────-┬-───────-┐
 │ Method        │  Line   │
 ├-─────────────-┼-───────-┤
 │ _initialize,0 │ 100.00% │
 │ decimals,0    │ 100.00% │
 │ myMethod,0    │ 100.00% │
 │ symbol,0      │ 100.00% │
 │ totalSupply,0 │ 100.00% │
 │ verify,0      │ 100.00% │
 │ balanceOf,1   │  99.15% │
 │ setOwner,1    │  97.92% │
 │ getOwner,0    │  95.24% │
 │ _deploy,2     │  94.44% │
 │ update,3      │  92.31% │
 │ burn,2        │  91.67% │
 │ mint,2        │  91.67% │
 │ transfer,4    │  91.40% │
 └-─────────────-┴-───────-┘

2024-02-16 18:48 UTC, cschuchardt88 commented
@shargon can we `test` to make sure the `smart contracts` are `within` the `limits` of the `vm`?

2024-02-16 19:58 UTC, shargon commented
Merge? @neo-project/core

2024-02-17 00:05 UTC, vncoelho approved these changes

2024-02-17 00:08 UTC, vncoelho commented
For reference about .devcontainer and coverlet use for this PR:

Go to https://github.com/neo-project/neo-devpack-dotnet/tree/core-nep-17-test

Click on Create Codespace
![image](https://github.com/neo-project/neo-devpack-dotnet/assets/17395762/857cc0d1-fdf1-4a40-8402-8227aaa06cad)

Wait until it is fully loadded and then type on terminal:

```cs
dotnet test ./tests/Neo.SmartContract.Template.UnitTests \
        --no-build \
        -l "console;verbosity=detailed" \
        -p:CollectCoverage=true \
        -p:Exclude=\"[Neo.Compiler.CSharp.UnitTests]*\" \
        -p:CoverletOutputFormat=lcov
```

2024-02-17 00:09 UTC, merged