[Framework and Examples] Update examples
neo-project/neo-devpack-dotnet pull request #993
Opened 2024-03-14 07:59 UTC by Jim8y

This pr adds an Oracle method name and update the Examples

2024-03-14 17:47 UTC, AnnaShaleva commented on examples/Directory.Build.props
> +    <Target Name="ExecuteBBeforeBuild" BeforeTargets="PreBuildEvent">
Typo in name.

2024-03-14 17:47 UTC, AnnaShaleva commented on examples/Example.SmartContract.NEP17/SampleNep17Token.cs
>              Storage.Put(new[] { PrefixMinter }, newMinter);
Then need `public static void SetMinter(UInt160? newMinter)`

2024-03-14 17:47 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Method.cs
> +    public const string OnOracleResponse = "onOracleResponse";
It should not be moved to a separate framework-wide constant, because name of the method is customizable. It's not a standard, it's just a single example.

2024-03-14 17:47 UTC, AnnaShaleva commented on src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
> +    [ContractVersion("<Version String Here>")]
Email is gone, but it's useful when email is present in the example.

2024-03-15 13:06 UTC, shargon commented on examples/Directory.Build.props
> +    <Target Name="ExecuteBBeforeBuild" BeforeTargets="PreBuildEvent">
```suggestion
    <Target Name="ExecuteBeforeBuild" BeforeTargets="PreBuildEvent">
```

2024-03-15 13:07 UTC, shargon commented on src/Neo.SmartContract.Template/templates/neocontractnep17/Nep17Contract.cs
> +    [ContractVersion("<Version String Here>")]
Agree we can add dev@neo.org in all of them

2024-03-15 13:22 UTC, cschuchardt88 requested changes

2024-03-15 13:22 UTC, cschuchardt88 commented on examples/Example.SmartContract.NEP17/SampleNep17Token.cs
> +            if (newMinter != null && newMinter.IsValid) return;
Should be
---
```csharp
if (newMinter != null && newMinter.IsValid)
{
  Storage.Put(new[] { PrefixMinter }, newMinter);
  OnSetMinter(newMinter);
}
```

2024-03-15 13:27 UTC, cschuchardt88 requested changes

2024-03-15 13:27 UTC, cschuchardt88 commented on examples/Example.SmartContract.NEP17/SampleNep17Token.cs
> +            if (newMinter != null && newMinter.IsValid) return;
This needs to `NOT` return, But instead set the `newMinter`.

2024-03-15 15:13 UTC, Jim8y commented on src/Neo.SmartContract.Framework/Method.cs
> +    public const string OnOracleResponse = "onOracleResponse";
This is not an NEP standard. Use it if people like, not use it if people not like. Just a tool.

2024-03-15 15:19 UTC, Jim8y commented
All addressed

2024-03-16 22:27 UTC, vncoelho reviewed
Looks very good and precise. I will test on Monday

2024-03-18 14:20 UTC, vncoelho reviewed
I tested most of them, some I also tested calling methods.

Oracle is not compiling
```cs
Internal git log: 
ebc056d731032a0c33cc97d90bd73493279c0401
COMPILING...

MSBuild version 17.7.4+3ebbd7c49 for .NET
  Determining projects to restore...
  Restored /neo-devpack-dotnet/src/Template.CSharpNeoCompiler/NeoCompilerContractGenerated.csproj (in 64 ms).
  1 of 2 projects are up-to-date for restore.
  Neo.SmartContract.Framework -> /neo-devpack-dotnet/src/Neo.SmartContract.Framework/bin/Debug/net7.0/Neo.SmartContract.Framework.dll
/neo-devpack-dotnet/src/Template.CSharpNeoCompiler/Contract1.cs(58,107): error CS0117: 'Method' does not contain a definition for 'OnOracleResponse' [/neo-devpack-dotnet/src/Template.CSharpNeoCompiler/NeoCompilerContractGenerated.csproj]

Build FAILED.

/neo-devpack-dotnet/src/Template.CSharpNeoCompiler/Contract1.cs(58,107): error CS0117: 'Method' does not contain a definition for 'OnOracleResponse' [/neo-devpack-dotnet/src/Template.CSharpNeoCompiler/NeoCompilerContractGenerated.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.13

Command dotnet build has been executed...results are below:

NEF is empty
MANIFEST is empty
```

2024-03-18 15:24 UTC, cschuchardt88 requested changes

2024-03-18 15:24 UTC, cschuchardt88 commented on examples/Example.SmartContract.Oracle/Oracle.cs
> +        public void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
```suggestion
        public static void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
```

2024-03-18 15:38 UTC, AnnaShaleva commented on src/Neo.SmartContract.Framework/Method.cs
> +    public const string OnOracleResponse = "onOracleResponse";
Still, this constant located near the NEP-related constants, and the description tells that `method that is called when a contract receives Oracle response.`. It's misleading to the end-user because it may be treated as "required" or "standard" name.

2024-03-18 16:48 UTC, vncoelho commented on examples/Example.SmartContract.Oracle/Oracle.cs
> +        public void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
```cs
Internal git log: 
ebc056d731032a0c33cc97d90bd73493279c0401
COMPILING...

MSBuild version 17.7.4+3ebbd7c49 for .NET
  Determining projects to restore...
  Restored /neo-devpack-dotnet/src/Template.CSharpNeoCompiler/NeoCompilerContractGenerated.csproj (in 64 ms).
  1 of 2 projects are up-to-date for restore.
  Neo.SmartContract.Framework -> /neo-devpack-dotnet/src/Neo.SmartContract.Framework/bin/Debug/net7.0/Neo.SmartContract.Framework.dll
/neo-devpack-dotnet/src/Template.CSharpNeoCompiler/Contract1.cs(28,48): error CS0736: 'SampleOracle' does not implement instance interface member 'IOracle.OnOracleResponse(string, object, OracleResponseCode, string)'. 'SampleOracle.OnOracleResponse(string, object, OracleResponseCode, string)' cannot implement the interface member because it is static. [/neo-devpack-dotnet/src/Template.CSharpNeoCompiler/NeoCompilerContractGenerated.csproj]

Build FAILED.

/neo-devpack-dotnet/src/Template.CSharpNeoCompiler/Contract1.cs(28,48): error CS0736: 'SampleOracle' does not implement instance interface member 'IOracle.OnOracleResponse(string, object, OracleResponseCode, string)'. 'SampleOracle.OnOracleResponse(string, object, OracleResponseCode, string)' cannot implement the interface member because it is static. [/neo-devpack-dotnet/src/Template.CSharpNeoCompiler/NeoCompilerContractGenerated.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.14

Command dotnet build has been executed...results are below:

NEF is empty
MANIFEST is empty
```

2024-03-18 16:49 UTC, vncoelho commented
The only compiling error was in the Oracle examples. Fixing it I think it could be merged and later we improve and verify other points.

2024-03-19 06:10 UTC, Jim8y commented on examples/Example.SmartContract.Oracle/Oracle.cs
> +        public void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
@cschuchardt88 it does not matter if its static or not, the compiler consider them the same.

2024-03-19 08:43 UTC, cschuchardt88 commented on examples/Example.SmartContract.Oracle/Oracle.cs
> +        public void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
> @cschuchardt88 it does not matter if its static or not, the compiler consider them the same.

Yes, I know but to keep it same as before.

2024-03-19 08:44 UTC, Jim8y commented on examples/Example.SmartContract.Oracle/Oracle.cs
> +        public void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
But how to make it an interface?

2024-03-19 08:46 UTC, cschuchardt88 commented on examples/Example.SmartContract.Oracle/Oracle.cs
> +        public void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
> But how to make it an interface?

```csharp
Public Interface
{
  public static void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString);
}
```

2024-03-19 08:54 UTC, Jim8y commented on examples/Example.SmartContract.Oracle/Oracle.cs
> +        public void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
Awesome

2024-03-19 13:56 UTC, shargon commented on examples/Example.SmartContract.NEP17/SampleNep17Token.cs
>              Storage.Put(new[] { PrefixMinter }, newMinter);
`IsValid` already check that is null

2024-03-19 13:56 UTC, shargon commented on examples/Example.SmartContract.NEP17/SampleNep17Token.cs
> +            if (newMinter != null && !newMinter.IsValid) return;
```suggestion
            if (!newMinter.IsValid) return;
```

2024-03-19 14:22 UTC, shargon commented on examples/Example.SmartContract.Oracle/Oracle.cs
> +        public void OnOracleResponse(string requestedUrl, object userData, OracleResponseCode oracleResponse, string jsonString)
Why in some `static` and in others don't?

2024-03-19 14:23 UTC, shargon approved these changes

2024-03-19 21:46 UTC, vncoelho requested changes
@Jim8y, before merging, please remove or fix the oracle example.

2024-03-20 07:38 UTC, cschuchardt88 commented
@vncoelho we are waiting on PR #998?

2024-03-20 14:07 UTC, merged